use flatc_rs_schema::resolved::ResolvedSchema;
use flatc_rs_schema::BaseType;

use super::code_writer::CodeWriter;
use super::dart_enum_gen;
use super::dart_struct_gen;
use super::dart_type_map;
use super::namespace_tree::{self, NamespaceNode, TypeEntry};
use super::type_map;
use super::CodeGenError;
use super::{field_id, field_type_index, DartCodeGenOptions};

/// Main Dart code generator.
pub struct DartGenerator<'a> {
    pub schema: &'a ResolvedSchema,
    pub w: CodeWriter,
    pub opts: &'a DartCodeGenOptions,
}

impl<'a> DartGenerator<'a> {
    pub fn new(schema: &'a ResolvedSchema, opts: &'a DartCodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            opts,
        }
    }

    /// Generate all Dart code and return the source string.
    pub fn generate(mut self) -> Result<String, CodeGenError> {
        self.gen_header();
        self.gen_body()?;
        Ok(self.w.finish())
    }

    fn gen_header(&mut self) {
        self.w
            .line("// automatically generated by flatc-rs, do not modify");
        self.w.line(
            "// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable",
        );
        self.w.blank();
    }

    /// Group all types by namespace and emit them.
    fn gen_body(&mut self) -> Result<(), CodeGenError> {
        let root = namespace_tree::build_namespace_tree(self.schema, &self.opts.gen_only_files);

        // Emit root namespace
        self.w.line("library;");
        self.w.blank();
        self.w.line("import 'dart:typed_data' show Uint8List;");
        self.w.blank();
        self.w
            .line("import 'package:flat_buffers/flat_buffers.dart' as fb;");
        self.w.blank();

        // Emit root-level types
        if !root.types.is_empty() {
            self.w.blank();
            for entry in &root.types {
                self.gen_type_entry(entry, "")?;
            }
        }

        // Emit child namespaces
        for (name, child) in &root.children {
            self.gen_namespace(name, child)?;
        }
        Ok(())
    }

    fn gen_namespace(&mut self, name: &str, node: &NamespaceNode) -> Result<(), CodeGenError> {
        self.w.blank();
        self.w.line(&format!("library {name};"));
        self.w.blank();
        self.w.line("import 'dart:typed_data' show Uint8List;");
        self.w.blank();
        self.w
            .line("import 'package:flat_buffers/flat_buffers.dart' as fb;");
        self.w.blank();

        // Import child namespaces
        for child_name in node.children.keys() {
            let child_ns = if name.is_empty() {
                child_name.to_string()
            } else {
                format!("{name}.{child_name}")
            };
            self.w.line(&format!(
                "import './{}_generated.dart';",
                child_ns.replace('.', "_")
            ));
        }
        self.w.blank();

        // Types at this namespace level
        for entry in &node.types {
            self.gen_type_entry(entry, name)?;
        }

        // Child namespaces
        for (child_name, child_node) in &node.children {
            self.gen_namespace(&format!("{name}.{child_name}"), child_node)?;
        }

        Ok(())
    }

    fn gen_type_entry(&mut self, entry: &TypeEntry, ns: &str) -> Result<(), CodeGenError> {
        match entry {
            TypeEntry::Enum(idx) => {
                dart_enum_gen::generate(&mut self.w, self.schema, *idx, self.opts.gen_object_api)?;
                self.w.blank();
            }
            TypeEntry::Struct(idx) => {
                dart_struct_gen::generate(&mut self.w, self.schema, *idx, self.opts.gen_object_api);
                self.w.blank();
            }
            TypeEntry::Table(idx) => {
                self.gen_table(*idx, ns)?;
                self.w.blank();
            }
        }
        Ok(())
    }

    /// Generate a Dart table.
    fn gen_table(&mut self, index: usize, _ns: &str) -> Result<(), CodeGenError> {
        let obj = &self.schema.objects[index];
        let name = &obj.name;

        dart_type_map::gen_doc_comment(&mut self.w, obj.documentation.as_ref());

        // Main class with private constructor
        self.w.line(&format!("class {name} {{"));
        self.w.indent();

        // Private constructor
        self.w.line(&format!("{name}._(this._bc, this._bcOffset);"));
        self.w.blank();

        // Factory constructor from bytes
        self.w.line(&format!("factory {name}(List<int> bytes) {{"));
        self.w.indent();
        self.w
            .line("final rootRef = fb.BufferContext.fromBytes(bytes);");
        self.w.line("return reader.read(rootRef, 0);");
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // Static reader
        self.w.line(&format!(
            "static const fb.Reader<{name}> reader = _{name}Reader();"
        ));
        self.w.blank();

        // Private fields
        self.w.line("final fb.BufferContext _bc;");
        self.w.line("final int _bcOffset;");
        self.w.blank();

        // Field accessors (skip deprecated)
        for field in &obj.fields {
            if field.is_deprecated {
                continue;
            }
            dart_type_map::gen_doc_comment(&mut self.w, field.documentation.as_ref());
            self.gen_table_field_accessor(field)?;
            self.w.blank();
        }

        // toString
        self.w.line("@override");
        self.w.line("String toString() {");
        self.w.indent();
        let fields_str = obj
            .fields
            .iter()
            .filter(|f| !f.is_deprecated)
            .map(|f| {
                let fname =
                    dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&f.name));
                format!("{fname}: ${{{fname}}}")
            })
            .collect::<Vec<_>>()
            .join(", ");
        self.w.line(&format!("return '{name}{{{fields_str}}}';"));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // unpack and pack
        if self.opts.gen_object_api {
            let unpack_args = obj
                .fields
                .iter()
                .filter(|f| !f.is_deprecated)
                .map(|f| {
                    let fname =
                        dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&f.name));
                    format!("{fname}: {fname}?.unpack()")
                })
                .collect::<Vec<_>>()
                .join(", ");
            self.w
                .line(&format!("{name}T unpack() => {name}T({unpack_args});"));
            self.w.blank();

            self.w.line(&format!(
                "static int pack(fb.Builder fbBuilder, {name}T? object) {{",
            ));
            self.w.indent();
            self.w.line("if (object == null) return 0;");
            self.w.line("return object.pack(fbBuilder);");
            self.w.dedent();
            self.w.line("}");
        }

        self.w.dedent();
        self.w.line("}");

        // TableReader class
        self.w.blank();
        self.w.line(&format!(
            "class _{name}Reader extends fb.TableReader<{name}> {{"
        ));
        self.w.indent();
        self.w.line(&format!("const _{name}Reader();"));
        self.w.blank();
        self.w.line("@override");
        self.w.line(&format!(
            "{name} createObject(fb.BufferContext bc, int offset) =>",
        ));
        self.w.indent();
        self.w.line(&format!("{name}._(bc, offset);"));
        self.w.dedent();
        self.w.dedent();
        self.w.line("}");

        // Builder class
        self.w.blank();
        self.w.line(&format!("class {name}Builder {{"));
        self.w.indent();
        self.w.line(&format!("{name}Builder(this.fbBuilder);"));
        self.w.blank();
        self.w.line("final fb.Builder fbBuilder;");
        self.w.blank();

        // begin method
        let field_count = obj.fields.iter().filter(|f| !f.is_deprecated).count();
        self.w.line("void begin() {");
        self.w.indent();
        self.w
            .line(&format!("fbBuilder.startTable({field_count});"));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // add methods
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            self.gen_table_add_method(field, name)?;
            self.w.blank();
        }

        // finish method
        self.w.line("int finish() {");
        self.w.indent();
        self.w.line("return fbBuilder.endTable();");
        self.w.dedent();
        self.w.line("}");

        self.w.dedent();
        self.w.line("}");

        // ObjectBuilder and T class
        if self.opts.gen_object_api {
            self.w.blank();
            self.gen_table_object_api_class(obj, name)?;
            self.w.blank();
            self.gen_table_object_builder(obj, name)?;
        }

        Ok(())
    }

    fn gen_table_field_accessor(
        &mut self,
        field: &flatc_rs_schema::resolved::ResolvedField,
    ) -> Result<(), CodeGenError> {
        let fname = dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
        let bt = field.type_.base_type;
        let slot = field_id(field).unwrap();
        let vt_offset = 4 + 2 * slot;

        match bt {
            BaseType::BASE_TYPE_BOOL => {
                self.w.line(&format!(
                    "bool get {fname} => const fb.Int8Reader().vTableGet(_bc, _bcOffset, {vt_offset}, 0) != 0;",
                    fname = fname, vt_offset = vt_offset
                ));
            }
            bt if type_map::is_scalar(bt) => {
                if type_map::has_type_index(field) {
                    // Enum field
                    let enum_idx = field_type_index(field).unwrap();
                    let enum_def = &self.schema.enums[enum_idx];
                    let enum_name = &enum_def.name;
                    let read_method = dart_type_map::bb_read_method(bt);
                    let default_val = field.default_integer.unwrap_or(0);
                    if field.is_optional {
                        self.w.line(&format!(
                            "{enum_name}? get {fname} => {enum_name}._createOrNull(",
                            enum_name = enum_name,
                            fname = fname
                        ));
                        self.w.indent();
                        self.w.line(&format!(
                            "const fb.{read_method}().vTableGetNullable(_bc, _bcOffset, {vt_offset}));",
                            read_method = read_method, vt_offset = vt_offset
                        ));
                        self.w.dedent();
                    } else {
                        self.w.line(&format!(
                            "{enum_name} get {fname} => {enum_name}.fromValue(",
                            enum_name = enum_name,
                            fname = fname
                        ));
                        self.w.indent();
                        self.w.line(&format!(
                            "const fb.{read_method}().vTableGet(_bc, _bcOffset, {vt_offset}, {default_val}));",
                            read_method = read_method, vt_offset = vt_offset, default_val = default_val
                        ));
                        self.w.dedent();
                    }
                } else {
                    let dart_type = dart_type_map::scalar_dart_type(bt);
                    let read_method = dart_type_map::bb_read_method(bt);
                    let default_val = if type_map::is_float(bt) {
                        field
                            .default_real
                            .unwrap_or(field.default_integer.unwrap_or(0) as f64)
                    } else {
                        field.default_integer.unwrap_or(0) as f64
                    };
                    let default_str = if type_map::is_float(bt) {
                        dart_type_map::format_default_real(default_val, bt)
                    } else {
                        dart_type_map::format_default(default_val as i64, bt)
                    };
                    if field.is_optional {
                        self.w.line(&format!(
                            "{dart_type}? get {fname} => const fb.{read_method}().vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                            dart_type = dart_type, fname = fname, read_method = read_method, vt_offset = vt_offset
                        ));
                    } else {
                        self.w.line(&format!(
                            "{dart_type} get {fname} => const fb.{read_method}().vTableGet(_bc, _bcOffset, {vt_offset}, {default_str});",
                            dart_type = dart_type, fname = fname, read_method = read_method, vt_offset = vt_offset, default_str = default_str
                        ));
                    }
                }
            }
            BaseType::BASE_TYPE_STRING => {
                let default_str = field.default_string.as_deref().unwrap_or("");
                if default_str.is_empty() {
                    self.w.line(&format!(
                        "String? get {fname} => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                        fname = fname, vt_offset = vt_offset
                    ));
                } else {
                    self.w.line(&format!(
                        "String get {fname} => const fb.StringReader().vTableGet(_bc, _bcOffset, {vt_offset}, defaultValue: '{default_str}') ?? '';",
                        fname = fname, vt_offset = vt_offset, default_str = default_str
                    ));
                }
            }
            BaseType::BASE_TYPE_STRUCT => {
                let idx = field_type_index(field).unwrap();
                let struct_name = &self.schema.objects[idx].name;
                self.w.line(&format!(
                    "{struct_name}? get {fname} => {struct_name}.reader.vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                    struct_name = struct_name, fname = fname, vt_offset = vt_offset
                ));
            }
            BaseType::BASE_TYPE_TABLE => {
                let idx = field_type_index(field).unwrap();
                let table_name = &self.schema.objects[idx].name;
                self.w.line(&format!(
                    "{table_name}? get {fname} => {table_name}.reader.vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                    table_name = table_name, fname = fname, vt_offset = vt_offset
                ));
            }
            BaseType::BASE_TYPE_VECTOR => {
                self.gen_vector_accessor(field, vt_offset)?;
            }
            BaseType::BASE_TYPE_UNION => {
                // Union accessor - simplified for now
                self.w
                    .line(&format!("dynamic get {fname} {{", fname = fname));
                self.w.indent();
                self.w.line(&format!(
                    "final offset = _bc.offset(_bcOffset, {vt_offset});"
                ));
                self.w.line("if (offset == 0) return null;");
                self.w.line("return null;");
                self.w.dedent();
                self.w.line("}");
            }
            _ => {
                return Err(CodeGenError::Internal(format!(
                    "unexpected base_type {bt:?} in table field accessor"
                )))
            }
        }

        Ok(())
    }

    fn gen_vector_accessor(
        &mut self,
        field: &flatc_rs_schema::resolved::ResolvedField,
        vt_offset: u32,
    ) -> Result<(), CodeGenError> {
        let fname = dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
        let et = field.type_.element_type_or_none();

        match et {
            et if type_map::is_scalar(et) => {
                let dart_type = if type_map::has_type_index(field) {
                    let enum_idx = field_type_index(field).unwrap();
                    self.schema.enums[enum_idx].name.clone()
                } else {
                    dart_type_map::scalar_dart_type(et).to_string()
                };
                let read_method = dart_type_map::bb_read_method(et);
                self.w.line(&format!(
                    "{dart_type}? get {fname} => const fb.{read_method}().vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                    dart_type = dart_type, fname = fname, read_method = read_method, vt_offset = vt_offset
                ));
            }
            BaseType::BASE_TYPE_STRING => {
                self.w.line(&format!(
                    "String? get {fname} => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                    fname = fname, vt_offset = vt_offset
                ));
            }
            BaseType::BASE_TYPE_TABLE => {
                let idx = field_type_index(field).unwrap();
                let table_name = &self.schema.objects[idx].name;
                self.w.line(&format!(
                    "{table_name}? get {fname} => {table_name}.reader.vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                    table_name = table_name, fname = fname, vt_offset = vt_offset
                ));
            }
            BaseType::BASE_TYPE_STRUCT => {
                let idx = field_type_index(field).unwrap();
                let struct_name = &self.schema.objects[idx].name;
                self.w.line(&format!(
                    "{struct_name}? get {fname} => {struct_name}.reader.vTableGetNullable(_bc, _bcOffset, {vt_offset});",
                    struct_name = struct_name, fname = fname, vt_offset = vt_offset
                ));
            }
            _ => {
                return Err(CodeGenError::Internal(format!(
                    "unexpected element_type {et:?} in vector accessor"
                )))
            }
        }

        Ok(())
    }

    fn gen_table_add_method(
        &mut self,
        field: &flatc_rs_schema::resolved::ResolvedField,
        _table_name: &str,
    ) -> Result<(), CodeGenError> {
        let fname = dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
        let pascal =
            dart_type_map::escape_dart_keyword(&dart_type_map::to_pascal_case(&field.name));
        let bt = field.type_.base_type;
        let slot = field_id(field).unwrap();

        match bt {
            bt if type_map::is_scalar(bt) => {
                let dart_type = dart_type_map::scalar_dart_type(bt);

                if field.is_optional {
                    self.w.line(&format!(
                        "int add{pascal}({dart_type}? {fname}) {{",
                        pascal = pascal,
                        dart_type = dart_type,
                        fname = fname
                    ));
                    self.w.indent();
                    self.w
                        .line(&format!("fbBuilder.addInt32({}, {fname} ?? 0);", slot));
                    self.w.line("return fbBuilder.offset;");
                    self.w.dedent();
                    self.w.line("}");
                } else {
                    self.w.line(&format!(
                        "int add{pascal}({dart_type} {fname}) {{",
                        pascal = pascal,
                        dart_type = dart_type,
                        fname = fname
                    ));
                    self.w.indent();
                    self.w
                        .line(&format!("fbBuilder.addInt32({}, {fname});", slot));
                    self.w.line("return fbBuilder.offset;");
                    self.w.dedent();
                    self.w.line("}");
                }
            }
            BaseType::BASE_TYPE_STRING
            | BaseType::BASE_TYPE_TABLE
            | BaseType::BASE_TYPE_VECTOR
            | BaseType::BASE_TYPE_STRUCT
            | BaseType::BASE_TYPE_UNION => {
                self.w.line(&format!(
                    "int add{pascal}Offset(int? {fname}Offset) {{",
                    pascal = pascal,
                    fname = fname
                ));
                self.w.indent();
                self.w.line(&format!(
                    "fbBuilder.addOffset({}, {fname}Offset ?? 0);",
                    slot
                ));
                self.w.line("return fbBuilder.offset;");
                self.w.dedent();
                self.w.line("}");
            }
            _ => {
                return Err(CodeGenError::Internal(format!(
                    "unexpected base_type {bt:?} in table add method"
                )))
            }
        }

        Ok(())
    }

    fn gen_table_object_builder(
        &mut self,
        obj: &flatc_rs_schema::resolved::ResolvedObject,
        name: &str,
    ) -> Result<(), CodeGenError> {
        self.w.line(&format!(
            "class {name}ObjectBuilder extends fb.ObjectBuilder {{"
        ));
        self.w.indent();

        // Fields for the builder
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            let bt = field.type_.base_type;
            let dart_type = if bt == BaseType::BASE_TYPE_STRING {
                "String".to_string()
            } else if bt == BaseType::BASE_TYPE_TABLE
                || bt == BaseType::BASE_TYPE_STRUCT
                || bt == BaseType::BASE_TYPE_VECTOR
                || bt == BaseType::BASE_TYPE_UNION
            {
                "int".to_string()
            } else {
                dart_type_map::scalar_dart_type(bt).to_string()
            };

            if field.is_optional
                || bt == BaseType::BASE_TYPE_STRING
                || bt == BaseType::BASE_TYPE_TABLE
                || bt == BaseType::BASE_TYPE_STRUCT
                || bt == BaseType::BASE_TYPE_VECTOR
                || bt == BaseType::BASE_TYPE_UNION
            {
                self.w.line(&format!("final {dart_type}? _{fname};"));
            } else {
                self.w.line(&format!("final {dart_type} _{fname};"));
            }
        }
        self.w.blank();

        // Constructor
        self.w.line(&format!("{name}ObjectBuilder({{"));
        self.w.indent();
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            self.w.line(&format!("this._{fname},"));
        }
        self.w.dedent();
        self.w.line("});");
        self.w.blank();

        // finish method
        self.w.line("@override");
        self.w.line("int finish(fb.Builder fbBuilder) {");
        self.w.indent();
        self.w.line(&format!(
            "fbBuilder.startTable({});",
            obj.fields.iter().filter(|f| !f.is_deprecated).count()
        ));
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            let bt = field.type_.base_type;
            let slot = field_id(field).unwrap();

            match bt {
                bt if type_map::is_scalar(bt) => {
                    if field.is_optional {
                        self.w.line(&format!(
                            "if (_{fname} != null) fbBuilder.addInt32({}, _{fname});",
                            slot
                        ));
                    } else {
                        self.w
                            .line(&format!("fbBuilder.addInt32({}, _{fname});", slot));
                    }
                }
                BaseType::BASE_TYPE_STRING => {
                    self.w.line(&format!(
                        "final int {fname}Offset = _{fname} != null ? fbBuilder.writeString(_{fname}) : 0;",
                        fname = fname
                    ));
                    self.w
                        .line(&format!("fbBuilder.addOffset({}, {fname}Offset);", slot));
                }
                BaseType::BASE_TYPE_TABLE
                | BaseType::BASE_TYPE_VECTOR
                | BaseType::BASE_TYPE_STRUCT
                | BaseType::BASE_TYPE_UNION => {
                    self.w.line(&format!(
                        "final int? {fname}Offset = _{fname}?.pack(fbBuilder);",
                        fname = fname
                    ));
                    self.w.line(&format!(
                        "fbBuilder.addOffset({}, {fname}Offset ?? 0);",
                        slot
                    ));
                }
                _ => {
                    return Err(CodeGenError::Internal(format!(
                        "unexpected base_type {bt:?} in table object builder"
                    )))
                }
            }
        }
        self.w.line("return fbBuilder.endTable();");
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // toBytes method
        self.w.line("@override");
        self.w.line("Uint8List toBytes([String? fileIdentifier]) {");
        self.w.indent();
        self.w
            .line("final fbBuilder = fb.Builder(deduplicateTables: false);");
        self.w
            .line("fbBuilder.finish(finish(fbBuilder), fileIdentifier);");
        self.w.line("return fbBuilder.buffer;");
        self.w.dedent();
        self.w.line("}");

        self.w.dedent();
        self.w.line("}");

        Ok(())
    }

    /// Generate the Object API T class for a table.
    /// This class is used with the Object API to create table instances.
    fn gen_table_object_api_class(
        &mut self,
        obj: &flatc_rs_schema::resolved::ResolvedObject,
        name: &str,
    ) -> Result<(), CodeGenError> {
        let t_name = format!("{name}T");

        self.w
            .line(&format!("class {t_name} implements fb.Packable {{"));
        self.w.indent();

        // Fields - use public field names (not underscore prefixed)
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            let bt = field.type_.base_type;
            let dart_type = self.table_field_dart_type(field, bt);
            if self.is_optional_or_reference_type(bt) {
                self.w.line(&format!("{dart_type}? {fname};"));
            } else {
                self.w.line(&format!("{dart_type} {fname};"));
            }
        }
        self.w.blank();

        // Constructor
        self.w.line(&format!("{t_name}({{"));
        self.w.indent();
        for (i, field) in obj.fields.iter().filter(|f| !f.is_deprecated).enumerate() {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            let bt = field.type_.base_type;
            let default = self.table_field_default(field, bt);
            let comma = if i < obj.fields.iter().filter(|f| !f.is_deprecated).count() - 1 {
                ","
            } else {
                ""
            };
            if default == "null" {
                self.w.line(&format!("this.{fname}{comma}"));
            } else {
                self.w.line(&format!("this.{fname} = {default}{comma}"));
            }
        }
        self.w.dedent();
        self.w.line("});");
        self.w.blank();

        // pack method
        self.w.line("@override");
        self.w.line("int pack(fb.Builder fbBuilder) {");
        self.w.indent();

        // First, pre-create strings and nested structures (get their offsets)
        // Collect all offsets first
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            let bt = field.type_.base_type;
            if bt == BaseType::BASE_TYPE_STRING {
                self.w.line(&format!(
                    "final int {fname}Offset = {fname} != null ? fbBuilder.writeString({fname}) : 0;",
                    fname = fname
                ));
            } else if bt == BaseType::BASE_TYPE_TABLE
                || bt == BaseType::BASE_TYPE_STRUCT
                || bt == BaseType::BASE_TYPE_VECTOR
                || bt == BaseType::BASE_TYPE_UNION
            {
                self.w.line(&format!(
                    "final int? {fname}Offset = {fname}?.pack(fbBuilder);",
                    fname = fname
                ));
            }
        }

        // Start table
        self.w.line(&format!(
            "fbBuilder.startTable({});",
            obj.fields.iter().filter(|f| !f.is_deprecated).count()
        ));

        // Add fields in order (not reverse for tables)
        for field in obj.fields.iter().filter(|f| !f.is_deprecated) {
            let fname =
                dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&field.name));
            let bt = field.type_.base_type;
            let slot = field_id(field).unwrap();

            match bt {
                bt if type_map::is_scalar(bt) => {
                    if field.is_optional {
                        self.w.line(&format!(
                            "if ({fname} != null) fbBuilder.addInt32({}, {fname});",
                            slot,
                            fname = fname
                        ));
                    } else {
                        self.w.line(&format!(
                            "fbBuilder.addInt32({}, {fname});",
                            slot,
                            fname = fname
                        ));
                    }
                }
                BaseType::BASE_TYPE_STRING => {
                    self.w.line(&format!(
                        "fbBuilder.addOffset({}, {fname}Offset);",
                        slot,
                        fname = fname
                    ));
                }
                BaseType::BASE_TYPE_TABLE
                | BaseType::BASE_TYPE_STRUCT
                | BaseType::BASE_TYPE_VECTOR
                | BaseType::BASE_TYPE_UNION => {
                    self.w.line(&format!(
                        "fbBuilder.addOffset({}, {fname}Offset ?? 0);",
                        slot,
                        fname = fname
                    ));
                }
                _ => {}
            }
        }

        self.w.line("return fbBuilder.endTable();");
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // toString
        self.w.line("@override");
        self.w.line("String toString() {");
        self.w.indent();
        let fields_str = obj
            .fields
            .iter()
            .filter(|f| !f.is_deprecated)
            .map(|f| {
                let fname =
                    dart_type_map::escape_dart_keyword(&dart_type_map::to_camel_case(&f.name));
                format!("{fname}: ${{{fname}}}")
            })
            .collect::<Vec<_>>()
            .join(", ");
        self.w.line(&format!("return '{t_name}{{{fields_str}}}';"));
        self.w.dedent();
        self.w.line("}");

        self.w.dedent();
        self.w.line("}");

        Ok(())
    }

    /// Get the Dart type for a table field.
    fn table_field_dart_type(
        &self,
        field: &flatc_rs_schema::resolved::ResolvedField,
        bt: BaseType,
    ) -> String {
        if bt == BaseType::BASE_TYPE_STRING {
            return "String".to_string();
        }
        if bt == BaseType::BASE_TYPE_STRUCT {
            let idx = field_type_index(field).unwrap();
            return self.schema.objects[idx].name.clone();
        }
        if bt == BaseType::BASE_TYPE_TABLE {
            let idx = field_type_index(field).unwrap();
            return self.schema.objects[idx].name.clone();
        }
        if bt == BaseType::BASE_TYPE_VECTOR {
            let et = field.type_.element_type_or_none();
            if et == BaseType::BASE_TYPE_STRUCT {
                let idx = field_type_index(field).unwrap();
                let struct_name = &self.schema.objects[idx].name;
                return format!("({struct_name})");
            }
            if et == BaseType::BASE_TYPE_TABLE {
                let idx = field_type_index(field).unwrap();
                let table_name = &self.schema.objects[idx].name;
                return format!("({table_name})");
            }
            if et == BaseType::BASE_TYPE_STRING {
                return "(String)".to_string();
            }
            // Check for enum in vector
            if type_map::is_scalar(et) && type_map::has_type_index(field) {
                let enum_idx = field_type_index(field).unwrap();
                return format!("({})", self.schema.enums[enum_idx].name);
            }
            if et == BaseType::BASE_TYPE_UNION {
                return "(dynamic)".to_string();
            }
            return format!("({})", dart_type_map::scalar_dart_type(et));
        }
        if bt == BaseType::BASE_TYPE_UNION {
            return "dynamic".to_string();
        }
        // Check for enum
        if type_map::is_scalar(bt) && type_map::has_type_index(field) {
            let enum_idx = field_type_index(field).unwrap();
            return self.schema.enums[enum_idx].name.clone();
        }
        dart_type_map::scalar_dart_type(bt).to_string()
    }

    /// Check if a field type is optional or a reference type.
    fn is_optional_or_reference_type(&self, bt: BaseType) -> bool {
        matches!(
            bt,
            BaseType::BASE_TYPE_STRING
                | BaseType::BASE_TYPE_TABLE
                | BaseType::BASE_TYPE_STRUCT
                | BaseType::BASE_TYPE_VECTOR
                | BaseType::BASE_TYPE_UNION
        )
    }

    /// Get the default value for a table field.
    fn table_field_default(
        &self,
        field: &flatc_rs_schema::resolved::ResolvedField,
        bt: BaseType,
    ) -> String {
        if field.is_optional {
            return "null".to_string();
        }
        match bt {
            BaseType::BASE_TYPE_STRING => "null".to_string(),
            BaseType::BASE_TYPE_BOOL => "false".to_string(),
            BaseType::BASE_TYPE_FLOAT | BaseType::BASE_TYPE_DOUBLE => "0.0".to_string(),
            BaseType::BASE_TYPE_TABLE
            | BaseType::BASE_TYPE_STRUCT
            | BaseType::BASE_TYPE_VECTOR
            | BaseType::BASE_TYPE_UNION => "null".to_string(),
            _ => "0".to_string(),
        }
    }
}
