//! Python model code generator for FlatBuffers schemas.
//!
//! This backend emits dependency-free Python dataclasses and IntEnum classes.
//! It intentionally models schema shape rather than FlatBuffers binary
//! encode/decode runtime behavior.

use flatc_rs_schema::resolved::{ResolvedField, ResolvedObject, ResolvedSchema, ResolvedType};
use flatc_rs_schema::{BaseType, Documentation};

use super::namespace_tree::{self, NamespaceNode, TypeEntry};
use super::{field_type_index, type_index, type_map, CodeGenError, PythonCodeGenOptions};
use codegen_core::CodeWriter;

/// Main Python code generator.
pub struct PythonGenerator<'a> {
    schema: &'a ResolvedSchema,
    w: CodeWriter,
    opts: &'a PythonCodeGenOptions,
}

impl<'a> PythonGenerator<'a> {
    pub fn new(schema: &'a ResolvedSchema, opts: &'a PythonCodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            opts,
        }
    }

    pub fn generate(mut self) -> Result<String, CodeGenError> {
        self.gen_header();
        self.gen_body()?;
        Ok(self.w.finish())
    }

    fn gen_header(&mut self) {
        self.w
            .line("# automatically generated by flatc-rs, do not modify");
        self.w.line("# @generated");
        self.w.line("from __future__ import annotations");
        self.w.blank();
        self.w.line("from dataclasses import dataclass, field");
        self.w.line("from enum import IntEnum");
        self.w.line("from typing import Any");
    }

    fn gen_body(&mut self) -> Result<(), CodeGenError> {
        let root = namespace_tree::build_namespace_tree(self.schema, &self.opts.gen_only_files);

        if !root.types.is_empty() {
            self.w.blank();
            self.gen_types(&root.types)?;
        }

        for (name, child) in &root.children {
            self.gen_namespace_node(name, child)?;
        }

        Ok(())
    }

    fn gen_namespace_node(&mut self, name: &str, node: &NamespaceNode) -> Result<(), CodeGenError> {
        self.w.blank();
        self.w.line(&format!("# namespace {name}"));

        if !node.types.is_empty() {
            self.w.blank();
            self.gen_types(&node.types)?;
        }

        for (child_name, child) in &node.children {
            self.gen_namespace_node(&format!("{name}.{child_name}"), child)?;
        }

        Ok(())
    }

    fn gen_types(&mut self, entries: &[TypeEntry]) -> Result<(), CodeGenError> {
        for entry in entries {
            match entry {
                TypeEntry::Enum(idx) => {
                    self.gen_enum(*idx)?;
                    self.w.blank();
                }
                TypeEntry::Struct(idx) | TypeEntry::Table(idx) => {
                    self.gen_object(*idx)?;
                    self.w.blank();
                }
            }
        }
        Ok(())
    }

    fn gen_enum(&mut self, index: usize) -> Result<(), CodeGenError> {
        let enum_def = &self.schema.enums[index];
        gen_doc_comment(&mut self.w, enum_def.documentation.as_ref());
        self.w
            .line(&format!("class {}(IntEnum):", class_name(&enum_def.name)));
        self.w.indent();
        if enum_def.values.is_empty() {
            self.w.line("pass");
        } else {
            for val in &enum_def.values {
                gen_doc_comment(&mut self.w, val.documentation.as_ref());
                self.w
                    .line(&format!("{} = {}", enum_variant_name(&val.name), val.value));
            }
        }
        self.w.dedent();
        Ok(())
    }

    fn gen_object(&mut self, index: usize) -> Result<(), CodeGenError> {
        let obj = &self.schema.objects[index];
        gen_doc_comment(&mut self.w, obj.documentation.as_ref());
        self.w.line("@dataclass(slots=True)");
        self.w.line(&format!("class {}:", class_name(&obj.name)));
        self.w.indent();

        if obj.fields.is_empty() {
            self.w.line("pass");
        } else {
            for field_desc in &obj.fields {
                self.gen_field(obj, field_desc)?;
            }
        }

        self.w.dedent();
        Ok(())
    }

    fn gen_field(
        &mut self,
        parent: &ResolvedObject,
        field_desc: &ResolvedField,
    ) -> Result<(), CodeGenError> {
        gen_doc_comment(&mut self.w, field_desc.documentation.as_ref());
        let name = py_identifier(&field_desc.name);
        let typ = self.field_type(parent, field_desc)?;
        let default = self.field_default(parent, field_desc)?;
        self.w.line(&format!("{name}: {typ} = {default}"));
        Ok(())
    }

    fn field_type(
        &self,
        parent: &ResolvedObject,
        field_desc: &ResolvedField,
    ) -> Result<String, CodeGenError> {
        let base = self.type_name(parent, field_desc, &field_desc.type_)?;
        if self.is_nullable_field(parent, field_desc) {
            Ok(format!("{base} | None"))
        } else {
            Ok(base)
        }
    }

    fn is_nullable_field(&self, parent: &ResolvedObject, field_desc: &ResolvedField) -> bool {
        if field_desc.is_optional {
            return true;
        }
        if parent.is_struct {
            return false;
        }
        matches!(
            field_desc.type_.base_type,
            BaseType::BASE_TYPE_STRING
                | BaseType::BASE_TYPE_TABLE
                | BaseType::BASE_TYPE_STRUCT
                | BaseType::BASE_TYPE_UNION
        ) && !field_desc.is_required
    }

    fn type_name(
        &self,
        parent: &ResolvedObject,
        field_desc: &ResolvedField,
        ty: &ResolvedType,
    ) -> Result<String, CodeGenError> {
        if ty.base_type.is_scalar() {
            if let Some(idx) = ty.index {
                let idx = idx as usize;
                if let Some(enum_def) = self.schema.enums.get(idx) {
                    return Ok(class_name(&enum_def.name));
                }
            }
        }

        match ty.base_type {
            BaseType::BASE_TYPE_BOOL => Ok("bool".to_string()),
            BaseType::BASE_TYPE_BYTE
            | BaseType::BASE_TYPE_U_BYTE
            | BaseType::BASE_TYPE_SHORT
            | BaseType::BASE_TYPE_U_SHORT
            | BaseType::BASE_TYPE_INT
            | BaseType::BASE_TYPE_U_INT
            | BaseType::BASE_TYPE_LONG
            | BaseType::BASE_TYPE_U_LONG
            | BaseType::BASE_TYPE_U_TYPE => Ok("int".to_string()),
            BaseType::BASE_TYPE_FLOAT | BaseType::BASE_TYPE_DOUBLE => Ok("float".to_string()),
            BaseType::BASE_TYPE_STRING => Ok("str".to_string()),
            BaseType::BASE_TYPE_TABLE | BaseType::BASE_TYPE_STRUCT => {
                let idx = field_type_index(field_desc)?;
                Ok(class_name(&self.schema.objects[idx].name))
            }
            BaseType::BASE_TYPE_UNION => Ok("Any".to_string()),
            BaseType::BASE_TYPE_VECTOR | BaseType::BASE_TYPE_VECTOR64 => {
                let elem = self.vector_element_type(parent, field_desc, ty)?;
                Ok(format!("list[{elem}]"))
            }
            BaseType::BASE_TYPE_ARRAY => {
                let elem = self.array_element_type(parent, field_desc, ty)?;
                Ok(format!("tuple[{elem}, ...]"))
            }
            BaseType::BASE_TYPE_NONE => Ok("None".to_string()),
        }
    }

    fn vector_element_type(
        &self,
        parent: &ResolvedObject,
        field_desc: &ResolvedField,
        ty: &ResolvedType,
    ) -> Result<String, CodeGenError> {
        let elem = ty.element_type_or_none();
        if elem.is_scalar() {
            if let Some(idx) = ty.index {
                let idx = idx as usize;
                if let Some(enum_def) = self.schema.enums.get(idx) {
                    return Ok(class_name(&enum_def.name));
                }
            }
        }
        match elem {
            BaseType::BASE_TYPE_TABLE | BaseType::BASE_TYPE_STRUCT => {
                let idx = field_type_index(field_desc)?;
                Ok(class_name(&self.schema.objects[idx].name))
            }
            BaseType::BASE_TYPE_UNION => Ok("Any".to_string()),
            BaseType::BASE_TYPE_STRING => Ok("str".to_string()),
            BaseType::BASE_TYPE_VECTOR | BaseType::BASE_TYPE_VECTOR64 => {
                Ok("list[Any]".to_string())
            }
            BaseType::BASE_TYPE_ARRAY => Ok("tuple[Any, ...]".to_string()),
            _ if elem.is_scalar() => self.type_name(
                parent,
                field_desc,
                &ResolvedType {
                    base_type: elem,
                    base_size: ty.base_size,
                    element_size: None,
                    element_type: None,
                    index: None,
                    fixed_length: None,
                },
            ),
            _ => {
                if let Some(index) = ty.index {
                    let idx = type_index(ty, &field_desc.name)?;
                    if self.schema.enums.get(idx).is_some() && index >= 0 {
                        return Ok(class_name(&self.schema.enums[idx].name));
                    }
                }
                Ok("Any".to_string())
            }
        }
    }

    fn array_element_type(
        &self,
        parent: &ResolvedObject,
        field_desc: &ResolvedField,
        ty: &ResolvedType,
    ) -> Result<String, CodeGenError> {
        let elem = ty.element_type_or_none();
        if elem == BaseType::BASE_TYPE_STRUCT {
            let idx = field_type_index(field_desc)?;
            return Ok(class_name(&self.schema.objects[idx].name));
        }
        if elem.is_scalar() {
            return self.type_name(
                parent,
                field_desc,
                &ResolvedType {
                    base_type: elem,
                    base_size: ty.base_size,
                    element_size: None,
                    element_type: None,
                    index: None,
                    fixed_length: None,
                },
            );
        }
        Ok("Any".to_string())
    }

    fn field_default(
        &self,
        parent: &ResolvedObject,
        field_desc: &ResolvedField,
    ) -> Result<String, CodeGenError> {
        if self.is_nullable_field(parent, field_desc) {
            return Ok("None".to_string());
        }

        if field_desc.type_.base_type.is_scalar() {
            if let (Some(enum_idx), Some(default_name)) =
                (field_desc.type_.index, field_desc.default_string.as_deref())
            {
                if let Some(enum_def) = self.schema.enums.get(enum_idx as usize) {
                    return Ok(format!(
                        "{}.{}",
                        class_name(&enum_def.name),
                        enum_variant_name(default_name)
                    ));
                }
            }
        }

        match field_desc.type_.base_type {
            BaseType::BASE_TYPE_BOOL => Ok(if field_desc.default_integer.unwrap_or(0) != 0 {
                "True".to_string()
            } else {
                "False".to_string()
            }),
            BaseType::BASE_TYPE_BYTE
            | BaseType::BASE_TYPE_U_BYTE
            | BaseType::BASE_TYPE_SHORT
            | BaseType::BASE_TYPE_U_SHORT
            | BaseType::BASE_TYPE_INT
            | BaseType::BASE_TYPE_U_INT
            | BaseType::BASE_TYPE_LONG
            | BaseType::BASE_TYPE_U_LONG
            | BaseType::BASE_TYPE_U_TYPE => Ok(field_desc.default_integer.unwrap_or(0).to_string()),
            BaseType::BASE_TYPE_FLOAT | BaseType::BASE_TYPE_DOUBLE => {
                Ok(format_float_default(field_desc.default_real.unwrap_or(0.0)))
            }
            BaseType::BASE_TYPE_STRING => Ok(match &field_desc.default_string {
                Some(s) => format!("{s:?}"),
                None => "None".to_string(),
            }),
            BaseType::BASE_TYPE_TABLE | BaseType::BASE_TYPE_UNION => Ok("None".to_string()),
            BaseType::BASE_TYPE_VECTOR | BaseType::BASE_TYPE_VECTOR64 => {
                Ok("field(default_factory=list)".to_string())
            }
            BaseType::BASE_TYPE_ARRAY => Ok("()".to_string()),
            BaseType::BASE_TYPE_STRUCT => {
                let idx = field_type_index(field_desc)?;
                let name = class_name(&self.schema.objects[idx].name);
                if parent.is_struct {
                    Ok(format!("field(default_factory={name})"))
                } else {
                    Ok("None".to_string())
                }
            }
            BaseType::BASE_TYPE_NONE => Ok("None".to_string()),
        }
    }
}

fn gen_doc_comment(w: &mut CodeWriter, doc: Option<&Documentation>) {
    let Some(doc) = doc else {
        return;
    };
    for line in &doc.lines {
        w.line(&format!("# {line}"));
    }
}

fn class_name(name: &str) -> String {
    let short = name.rsplit('.').next().unwrap_or(name);
    let candidate = type_map::to_pascal_case(short);
    if candidate.is_empty() {
        "Unknown".to_string()
    } else {
        sanitize_identifier(&candidate)
    }
}

fn enum_variant_name(name: &str) -> String {
    let candidate = type_map::to_upper_snake_case(name);
    if candidate.is_empty() {
        "UNKNOWN".to_string()
    } else {
        sanitize_identifier(&candidate)
    }
}

fn py_identifier(name: &str) -> String {
    let candidate = type_map::to_snake_case(name);
    let normalized = if candidate.is_empty() {
        "unknown".to_string()
    } else {
        candidate
    };
    sanitize_identifier(&normalized)
}

fn sanitize_identifier(name: &str) -> String {
    let prefixed = if name.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("_{name}")
    } else {
        name.to_string()
    };
    if is_python_keyword(&prefixed) {
        format!("{prefixed}_")
    } else {
        prefixed
    }
}

fn is_python_keyword(name: &str) -> bool {
    matches!(
        name,
        "False"
            | "None"
            | "True"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "break"
            | "class"
            | "continue"
            | "def"
            | "del"
            | "elif"
            | "else"
            | "except"
            | "finally"
            | "for"
            | "from"
            | "global"
            | "if"
            | "import"
            | "in"
            | "is"
            | "lambda"
            | "nonlocal"
            | "not"
            | "or"
            | "pass"
            | "raise"
            | "return"
            | "try"
            | "while"
            | "with"
            | "yield"
            | "match"
            | "case"
            | "type"
    )
}

fn format_float_default(value: f64) -> String {
    if value.is_nan() {
        "float('nan')".to_string()
    } else if value == f64::INFINITY {
        "float('inf')".to_string()
    } else if value == f64::NEG_INFINITY {
        "float('-inf')".to_string()
    } else if value == value.floor() {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}
