use flatc_rs_schema::resolved::ResolvedSchema;

use super::enum_gen;
use super::namespace_tree::{self, NamespaceNode, TypeEntry};
use super::rust_table_gen;
use super::struct_gen;
use super::type_map;
use super::{CodeGenError, CodeGenOptions};
use codegen_core::CodeWriter;

/// Main code generator. Holds a reference to the resolved schema and produces
/// Rust source code compatible with the `flatbuffers` runtime crate.
pub struct RustGenerator<'a> {
    pub schema: &'a ResolvedSchema,
    pub w: CodeWriter,
    pub opts: &'a CodeGenOptions,
}

impl<'a> RustGenerator<'a> {
    pub fn new(schema: &'a ResolvedSchema, opts: &'a CodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            opts,
        }
    }

    /// Generate all Rust code and return the source string.
    pub fn generate(mut self) -> Result<String, CodeGenError> {
        self.gen_header();
        self.gen_body()?;
        self.gen_root_type_functions();
        Ok(self.w.finish())
    }

    fn gen_header(&mut self) {
        self.w
            .line("// automatically generated by flatc-rs, do not modify");
        self.w.line("// @generated");
        self.w.blank();
        self.w.line("extern crate alloc;");
        if self.opts.rust_serialize {
            self.w.line("extern crate serde;");
        }
    }

    /// Group all types by namespace and emit nested `pub mod` blocks.
    fn gen_body(&mut self) -> Result<(), CodeGenError> {
        let root = namespace_tree::build_namespace_tree(self.schema, &self.opts.gen_only_files);

        // Emit root-level types first
        if !root.types.is_empty() {
            self.w.blank();
            self.gen_types(&root.types)?;
        }

        // Emit child namespace modules
        for (name, child) in &root.children {
            self.gen_namespace_node(name, child)?;
        }
        Ok(())
    }

    /// Recursively emit a namespace node as nested `pub mod` blocks.
    fn gen_namespace_node(&mut self, name: &str, node: &NamespaceNode) -> Result<(), CodeGenError> {
        let mod_name = type_map::to_snake_case(name);
        self.w.blank();
        self.w.line("#[allow(unused_imports, dead_code)]");
        self.w.line(&format!("pub mod {mod_name} {{"));
        self.w.indent();
        if !self.opts.no_includes {
            self.w.line("use super::*;");
        }

        // Types at this namespace level
        if !node.types.is_empty() {
            self.w.blank();
            self.gen_types(&node.types)?;
        }

        // Child namespaces
        for (child_name, child_node) in &node.children {
            self.gen_namespace_node(child_name, child_node)?;
        }

        self.w.dedent();
        self.w.line(&format!("}} // {name}"));
        Ok(())
    }

    fn gen_types(&mut self, entries: &[TypeEntry]) -> Result<(), CodeGenError> {
        for entry in entries {
            match entry {
                TypeEntry::Enum(idx) => {
                    enum_gen::generate(&mut self.w, self.schema, *idx, self.opts)?;
                    self.w.blank();
                }
                TypeEntry::Struct(idx) => {
                    struct_gen::generate(&mut self.w, self.schema, *idx, self.opts)?;
                    self.w.blank();
                }
                TypeEntry::Table(idx) => {
                    rust_table_gen::generate(&mut self.w, self.schema, *idx, self.opts)?;
                    self.w.blank();
                }
            }
        }
        Ok(())
    }

    fn gen_root_type_functions(&mut self) {
        let root_table = match self.schema.root_table_index {
            Some(idx) => &self.schema.objects[idx],
            None => return,
        };
        let name = &root_table.name;
        if name.is_empty() {
            return;
        }

        let ns = namespace_tree::namespace_str(root_table.namespace.as_ref());
        let full_name = if ns.is_empty() {
            name.to_string()
        } else {
            format!("{}::{}", ns.replace('.', "::"), name)
        };

        let snake = type_map::to_snake_case(name);
        let upper_snake = type_map::to_upper_snake_case(name);

        self.w.blank();
        // file_identifier constant
        if let Some(ref ident) = self.schema.file_ident {
            if !ident.is_empty() {
                self.w.line(&format!(
                    "pub const {upper_snake}_IDENTIFIER: &str = \"{ident}\";"
                ));
                self.w.blank();
            }
        }

        // root_as_* (verified)
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn root_as_{snake}(buf: &[u8]) -> Result<{full_name}<'_>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        self.w
            .line(&format!("::flatbuffers::root::<{full_name}>(buf)"));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // size_prefixed_root_as_*
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn size_prefixed_root_as_{snake}(buf: &[u8]) -> Result<{full_name}<'_>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        self.w.line(&format!(
            "::flatbuffers::size_prefixed_root::<{full_name}>(buf)"
        ));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // root_as_*_unchecked (unsafe)
        self.w.line("#[inline]");
        self.w.line("/// # Safety");
        self.w
            .line("/// Caller must ensure the buffer contains a valid FlatBuffer.");
        self.w.line(&format!(
            "pub unsafe fn root_as_{snake}_unchecked(buf: &[u8]) -> {full_name}<'_> {{"
        ));
        self.w.indent();
        self.w.line(&format!(
            "unsafe {{ ::flatbuffers::root_unchecked::<{full_name}>(buf) }}"
        ));
        self.w.dedent();
        self.w.line("}");

        // file_identifier functions
        if let Some(ref ident) = self.schema.file_ident {
            if !ident.is_empty() {
                self.w.blank();
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn {snake}_buffer_has_identifier(buf: &[u8]) -> bool {{"
                ));
                self.w.indent();
                self.w.line(&format!(
                    "::flatbuffers::buffer_has_identifier(buf, {upper_snake}_IDENTIFIER, false)"
                ));
                self.w.dedent();
                self.w.line("}");
                self.w.blank();

                // finish_*_buffer
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn finish_{snake}_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>("
                ));
                self.w.indent();
                self.w
                    .line("fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,");
                self.w
                    .line(&format!("root: ::flatbuffers::WIPOffset<{full_name}<'a>>,"));
                self.w.dedent();
                self.w.line(") {");
                self.w.indent();
                self.w.line(&format!(
                    "fbb.finish(root, Some({upper_snake}_IDENTIFIER));"
                ));
                self.w.dedent();
                self.w.line("}");
                self.w.blank();

                // finish_size_prefixed_*_buffer
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn finish_size_prefixed_{snake}_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>("
                ));
                self.w.indent();
                self.w
                    .line("fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,");
                self.w
                    .line(&format!("root: ::flatbuffers::WIPOffset<{full_name}<'a>>,"));
                self.w.dedent();
                self.w.line(") {");
                self.w.indent();
                self.w.line(&format!(
                    "fbb.finish_size_prefixed(root, Some({upper_snake}_IDENTIFIER));"
                ));
                self.w.dedent();
                self.w.line("}");
            }
        }
    }
}
