use std::collections::BTreeMap;

use flatc_rs_schema as schema;

use super::code_writer::CodeWriter;
use super::enum_gen;
use super::should_generate;
use super::struct_gen;
use super::table_gen;
use super::type_map;
use super::CodeGenOptions;

/// Main code generator. Holds a reference to the resolved schema and produces
/// Rust source code compatible with the `flatbuffers` runtime crate.
pub struct RustGenerator<'a> {
    pub schema: &'a schema::Schema,
    pub w: CodeWriter,
    pub _opts: &'a CodeGenOptions,
}

impl<'a> RustGenerator<'a> {
    pub fn new(schema: &'a schema::Schema, opts: &'a CodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            _opts: opts,
        }
    }

    /// Generate all Rust code and return the source string.
    pub fn generate(mut self) -> String {
        self.gen_header();
        self.gen_body();
        self.gen_root_type_functions();
        self.w.finish()
    }

    fn gen_header(&mut self) {
        self.w
            .line("// automatically generated by flatc-rs, do not modify");
        self.w.line("// @generated");
        self.w.blank();
        self.w.line("extern crate alloc;");
        if self._opts.rust_serialize {
            self.w.line("extern crate serde;");
        }
    }

    /// Group all types by namespace and emit nested `pub mod` blocks.
    fn gen_body(&mut self) {
        // Build a namespace tree so that shared prefixes produce a single
        // `pub mod` block (e.g., MyGame.Example and MyGame.Example2 share
        // `pub mod my_game`).
        let mut root = NamespaceNode::new();

        let filter = &self._opts.gen_only_files;

        for (i, enum_def) in self.schema.enums.iter().enumerate() {
            if !should_generate(enum_def.declaration_file.as_deref(), filter) {
                continue;
            }
            let ns = namespace_str(enum_def.namespace.as_ref());
            let parts: Vec<&str> = if ns.is_empty() {
                vec![]
            } else {
                ns.split('.').collect()
            };
            root.insert(&parts, TypeEntry::Enum(i));
        }

        for (i, obj) in self.schema.objects.iter().enumerate() {
            if !should_generate(obj.declaration_file.as_deref(), filter) {
                continue;
            }
            let ns = namespace_str(obj.namespace.as_ref());
            let parts: Vec<&str> = if ns.is_empty() {
                vec![]
            } else {
                ns.split('.').collect()
            };
            let entry = if obj.is_struct == Some(true) {
                TypeEntry::Struct(i)
            } else {
                TypeEntry::Table(i)
            };
            root.insert(&parts, entry);
        }

        // Emit root-level types first
        if !root.types.is_empty() {
            self.w.blank();
            self.gen_types(&root.types);
        }

        // Emit child namespace modules
        for (name, child) in &root.children {
            self.gen_namespace_node(name, child);
        }
    }

    /// Recursively emit a namespace node as nested `pub mod` blocks.
    fn gen_namespace_node(&mut self, name: &str, node: &NamespaceNode) {
        let mod_name = type_map::to_snake_case(name);
        self.w.blank();
        self.w.line("#[allow(unused_imports, dead_code)]");
        self.w.line(&format!("pub mod {mod_name} {{"));
        self.w.indent();
        self.w.line("use super::*;");

        // Types at this namespace level
        if !node.types.is_empty() {
            self.w.blank();
            self.gen_types(&node.types);
        }

        // Child namespaces
        for (child_name, child_node) in &node.children {
            self.gen_namespace_node(child_name, child_node);
        }

        self.w.dedent();
        self.w.line(&format!("}} // {name}"));
    }

    fn gen_types(&mut self, entries: &[TypeEntry]) {
        for entry in entries {
            match entry {
                TypeEntry::Enum(idx) => {
                    enum_gen::generate(&mut self.w, self.schema, *idx, self._opts);
                    self.w.blank();
                }
                TypeEntry::Struct(idx) => {
                    struct_gen::generate(&mut self.w, self.schema, *idx, self._opts);
                    self.w.blank();
                }
                TypeEntry::Table(idx) => {
                    table_gen::generate(&mut self.w, self.schema, *idx, self._opts);
                    self.w.blank();
                }
            }
        }
    }

    fn gen_root_type_functions(&mut self) {
        let root_table = match self.schema.root_table.as_ref() {
            Some(rt) => rt,
            None => return,
        };
        let name = root_table.name.as_deref().unwrap_or("");
        if name.is_empty() {
            return;
        }

        let ns = namespace_str(root_table.namespace.as_ref());
        let full_name = if ns.is_empty() {
            name.to_string()
        } else {
            format!("{}::{}", ns.replace('.', "::"), name)
        };

        let snake = type_map::to_snake_case(name);
        let upper_snake = type_map::to_upper_snake_case(name);

        self.w.blank();
        // file_identifier constant
        if let Some(ref ident) = self.schema.file_ident {
            if !ident.is_empty() {
                self.w.line(&format!(
                    "pub const {upper_snake}_IDENTIFIER: &str = \"{ident}\";"
                ));
                self.w.blank();
            }
        }

        // root_as_* (verified)
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn root_as_{snake}(buf: &[u8]) -> Result<{full_name}<'_>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        self.w
            .line(&format!("::flatbuffers::root::<{full_name}>(buf)"));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // size_prefixed_root_as_*
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn size_prefixed_root_as_{snake}(buf: &[u8]) -> Result<{full_name}<'_>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        self.w.line(&format!(
            "::flatbuffers::size_prefixed_root::<{full_name}>(buf)"
        ));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // root_as_*_unchecked (unsafe)
        self.w.line("#[inline]");
        self.w.line("/// # Safety");
        self.w
            .line("/// Caller must ensure the buffer contains a valid FlatBuffer.");
        self.w.line(&format!(
            "pub unsafe fn root_as_{snake}_unchecked(buf: &[u8]) -> {full_name}<'_> {{"
        ));
        self.w.indent();
        self.w.line(&format!(
            "unsafe {{ ::flatbuffers::root_unchecked::<{full_name}>(buf) }}"
        ));
        self.w.dedent();
        self.w.line("}");

        // file_identifier functions
        if let Some(ref ident) = self.schema.file_ident {
            if !ident.is_empty() {
                self.w.blank();
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn {snake}_buffer_has_identifier(buf: &[u8]) -> bool {{"
                ));
                self.w.indent();
                self.w.line(&format!(
                    "::flatbuffers::buffer_has_identifier(buf, {upper_snake}_IDENTIFIER, false)"
                ));
                self.w.dedent();
                self.w.line("}");
                self.w.blank();

                // finish_*_buffer
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn finish_{snake}_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>("
                ));
                self.w.indent();
                self.w
                    .line("fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,");
                self.w
                    .line(&format!("root: ::flatbuffers::WIPOffset<{full_name}<'a>>,"));
                self.w.dedent();
                self.w.line(") {");
                self.w.indent();
                self.w.line(&format!(
                    "fbb.finish(root, Some({upper_snake}_IDENTIFIER));"
                ));
                self.w.dedent();
                self.w.line("}");
                self.w.blank();

                // finish_size_prefixed_*_buffer
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn finish_size_prefixed_{snake}_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>("
                ));
                self.w.indent();
                self.w
                    .line("fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,");
                self.w
                    .line(&format!("root: ::flatbuffers::WIPOffset<{full_name}<'a>>,"));
                self.w.dedent();
                self.w.line(") {");
                self.w.indent();
                self.w.line(&format!(
                    "fbb.finish_size_prefixed(root, Some({upper_snake}_IDENTIFIER));"
                ));
                self.w.dedent();
                self.w.line("}");
            }
        }
    }
}

/// What kind of type an entry represents.
enum TypeEntry {
    Enum(usize),
    Struct(usize),
    Table(usize),
}

/// A tree node for grouping types by namespace hierarchy.
/// This prevents duplicate `pub mod` blocks when multiple namespaces share
/// a common prefix (e.g., `MyGame.Example` and `MyGame.Example2` both need
/// a single `pub mod my_game` wrapping their respective sub-modules).
struct NamespaceNode {
    children: BTreeMap<String, NamespaceNode>,
    types: Vec<TypeEntry>,
}

impl NamespaceNode {
    fn new() -> Self {
        Self {
            children: BTreeMap::new(),
            types: Vec::new(),
        }
    }

    /// Insert a type at the given namespace path (split into components).
    fn insert(&mut self, parts: &[&str], entry: TypeEntry) {
        if parts.is_empty() {
            self.types.push(entry);
        } else {
            self.children
                .entry(parts[0].to_string())
                .or_insert_with(NamespaceNode::new)
                .insert(&parts[1..], entry);
        }
    }
}

/// Extract namespace string from an optional Namespace message.
fn namespace_str(ns: Option<&schema::Namespace>) -> String {
    ns.and_then(|n| n.namespace.as_deref())
        .unwrap_or("")
        .to_string()
}
