use flatc_rs_schema::resolved::ResolvedSchema;

use super::enum_gen;
use super::namespace_tree::{self, NamespaceNode, TypeEntry};
use super::rust_runtime_gen;
use super::rust_table_gen;
use super::struct_gen;
use super::type_map;
use super::{CodeGenError, CodeGenOptions};
use codegen_core::CodeWriter;

/// Main code generator. Holds a reference to the resolved schema and produces
/// Rust source code compatible with the `flatbuffers` runtime crate.
pub struct RustGenerator<'a> {
    pub schema: &'a ResolvedSchema,
    pub w: CodeWriter,
    pub opts: &'a CodeGenOptions,
}

impl<'a> RustGenerator<'a> {
    pub fn new(schema: &'a ResolvedSchema, opts: &'a CodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            opts,
        }
    }

    /// Generate all Rust code and return the source string.
    pub fn generate(mut self) -> Result<String, CodeGenError> {
        self.gen_header();
        self.gen_body()?;
        Ok(self.w.finish())
    }

    fn gen_header(&mut self) {
        self.w
            .line("// automatically generated by the FlatBuffers compiler, do not modify");
        self.w.line("// @generated");
        self.w.line("extern crate alloc;");
        if self.opts.rust_serialize {
            self.w.line("extern crate serde;");
        }
        if self.opts.rust_pluggable_buffer {
            rust_runtime_gen::generate(&mut self.w);
        }
    }

    fn gen_doc_lines(&mut self, lines: &[&str]) {
        for line in lines {
            self.w.line(&format!("/// {line}"));
        }
    }

    /// Group all types by namespace and emit nested `pub mod` blocks.
    fn gen_body(&mut self) -> Result<(), CodeGenError> {
        let root = namespace_tree::build_namespace_tree(self.schema, &self.opts.gen_only_files);

        // Emit root-level types first
        if !root.types.is_empty() {
            self.w.blank();
            self.gen_types(&root.types)?;
        }

        // Emit child namespace modules
        for (name, child) in &root.children {
            self.gen_namespace_node(name, child)?;
        }
        Ok(())
    }

    /// Recursively emit a namespace node as nested `pub mod` blocks.
    fn gen_namespace_node(&mut self, name: &str, node: &NamespaceNode) -> Result<(), CodeGenError> {
        let mod_name = type_map::to_rust_snake_case(name);
        self.w.blank();
        self.w.line("#[allow(unused_imports, dead_code)]");
        self.w.line(&format!("pub mod {mod_name} {{"));
        self.w.indent();
        self.w.line("extern crate alloc;");
        if self.opts.rust_pluggable_buffer && !self.opts.no_includes {
            self.w.line("use super::*;");
        }

        // Types at this namespace level
        if !node.types.is_empty() {
            self.w.blank();
            self.gen_types(&node.types)?;
        }

        // Child namespaces
        for (child_name, child_node) in &node.children {
            self.gen_namespace_node(child_name, child_node)?;
        }

        self.w.dedent();
        self.w.line(&format!("}} // pub mod {name}"));
        Ok(())
    }

    fn gen_types(&mut self, entries: &[TypeEntry]) -> Result<(), CodeGenError> {
        for entry in entries {
            match entry {
                TypeEntry::Enum(idx) => {
                    enum_gen::generate(&mut self.w, self.schema, *idx, self.opts)?;
                    self.w.blank();
                }
                TypeEntry::Struct(idx) => {
                    struct_gen::generate(&mut self.w, self.schema, *idx, self.opts)?;
                    self.w.blank();
                }
                TypeEntry::Table(idx) => {
                    rust_table_gen::generate(&mut self.w, self.schema, *idx, self.opts)?;
                    self.w.blank();
                    if self.schema.root_table_index == Some(*idx) {
                        self.gen_root_type_functions(*idx);
                        self.w.blank();
                    }
                }
            }
        }
        Ok(())
    }

    fn gen_root_type_functions(&mut self, root_table_index: usize) {
        let root_table = &self.schema.objects[root_table_index];
        let name = &root_table.name;
        if name.is_empty() {
            return;
        }
        if !super::should_generate(
            root_table.declaration_file.as_deref(),
            &self.opts.gen_only_files,
        ) {
            return;
        }

        let snake = type_map::to_rust_snake_case(name);
        let upper_snake = type_map::to_rust_upper_snake_case(name);

        // root_as_* (verified)
        self.w.blank();
        self.gen_doc_lines(&[
            &format!("Verifies that a buffer of bytes contains a `{name}`"),
            "and returns it.",
            "Note that verification is still experimental and may not",
            "catch every error, or be maximally performant. For the",
            "previous, unchecked, behavior use",
            &format!("`root_as_{snake}_unchecked`."),
        ]);
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn root_as_{snake}(buf: &[u8]) -> Result<{name}<'_>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        if self.opts.rust_pluggable_buffer {
            self.w.line(&format!("root_as_{snake}_in::<[u8]>(buf)"));
        } else {
            self.w.line(&format!("::flatbuffers::root::<{name}>(buf)"));
        }
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        if self.opts.rust_pluggable_buffer {
            self.w.line("#[inline]");
            self.w.line(&format!(
                "pub fn root_as_{snake}_in<'a, B>(buf: &'a B) -> Result<{name}<'a, B>, ::flatbuffers::InvalidFlatbuffer>"
            ));
            self.w.line("where");
            self.w.indent();
            self.w
                .line("B: ?Sized + __flatc_rs_runtime::FlatBufferRead,");
            self.w.dedent();
            self.w.line("{");
            self.w.indent();
            self.w.line("let bytes = buf.all_bytes().ok_or(::flatbuffers::InvalidFlatbuffer::RangeOutOfBounds {");
            self.w.indent();
            self.w.line("range: 0..buf.len(),");
            self.w.line("error_trace: Default::default(),");
            self.w.dedent();
            self.w.line("})?;");
            self.w
                .line(&format!("::flatbuffers::root::<{name}>(bytes)?;"));
            self.w.line(&format!(
                "Ok(unsafe {{ {name}::init_from_buffer(buf, __flatc_rs_runtime::root_loc(buf)) }})"
            ));
            self.w.dedent();
            self.w.line("}");
            self.w.blank();
        }

        // size_prefixed_root_as_*
        self.gen_doc_lines(&[
            "Verifies that a buffer of bytes contains a size prefixed",
            &format!("`{name}` and returns it."),
            "Note that verification is still experimental and may not",
            "catch every error, or be maximally performant. For the",
            "previous, unchecked, behavior use",
            &format!("`size_prefixed_root_as_{snake}_unchecked`."),
        ]);
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn size_prefixed_root_as_{snake}(buf: &[u8]) -> Result<{name}<'_>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        if self.opts.rust_pluggable_buffer {
            self.w
                .line(&format!("size_prefixed_root_as_{snake}_in::<[u8]>(buf)"));
        } else {
            self.w
                .line(&format!("::flatbuffers::size_prefixed_root::<{name}>(buf)"));
        }
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        if self.opts.rust_pluggable_buffer {
            self.w.line("#[inline]");
            self.w.line(&format!(
                "pub fn size_prefixed_root_as_{snake}_in<'a, B>(buf: &'a B) -> Result<{name}<'a, B>, ::flatbuffers::InvalidFlatbuffer>"
            ));
            self.w.line("where");
            self.w.indent();
            self.w
                .line("B: ?Sized + __flatc_rs_runtime::FlatBufferRead,");
            self.w.dedent();
            self.w.line("{");
            self.w.indent();
            self.w.line("let bytes = buf.all_bytes().ok_or(::flatbuffers::InvalidFlatbuffer::RangeOutOfBounds {");
            self.w.indent();
            self.w.line("range: 0..buf.len(),");
            self.w.line("error_trace: Default::default(),");
            self.w.dedent();
            self.w.line("})?;");
            self.w.line(&format!(
                "::flatbuffers::size_prefixed_root::<{name}>(bytes)?;"
            ));
            self.w.line(&format!(
                "Ok(unsafe {{ {name}::init_from_buffer(buf, __flatc_rs_runtime::size_prefixed_root_loc(buf)) }})"
            ));
            self.w.dedent();
            self.w.line("}");
            self.w.blank();
        }

        // Verifier-options variants operate on the standard byte-slice reader.
        self.gen_doc_lines(&[
            "Verifies, with the given options, that a buffer of bytes",
            &format!("contains a `{name}` and returns it."),
            "Note that verification is still experimental and may not",
            "catch every error, or be maximally performant. For the",
            "previous, unchecked, behavior use",
            &format!("`root_as_{snake}_unchecked`."),
        ]);
        self.w.line("#[inline]");
        self.w
            .line(&format!("pub fn root_as_{snake}_with_opts<'b, 'o>("));
        self.w.indent();
        self.w.line("opts: &'o ::flatbuffers::VerifierOptions,");
        self.w.line("buf: &'b [u8],");
        self.w.dedent();
        self.w.line(&format!(
            ") -> Result<{name}<'b>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        self.w.line(&format!(
            "::flatbuffers::root_with_opts::<{name}<'b>>(opts, buf)"
        ));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        self.gen_doc_lines(&[
            "Verifies, with the given verifier options, that a buffer of",
            &format!("bytes contains a size prefixed `{name}` and returns"),
            "it. Note that verification is still experimental and may not",
            "catch every error, or be maximally performant. For the",
            "previous, unchecked, behavior use",
            &format!("`root_as_{snake}_unchecked`."),
        ]);
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn size_prefixed_root_as_{snake}_with_opts<'b, 'o>("
        ));
        self.w.indent();
        self.w.line("opts: &'o ::flatbuffers::VerifierOptions,");
        self.w.line("buf: &'b [u8],");
        self.w.dedent();
        self.w.line(&format!(
            ") -> Result<{name}<'b>, ::flatbuffers::InvalidFlatbuffer> {{"
        ));
        self.w.indent();
        self.w.line(&format!(
            "::flatbuffers::size_prefixed_root_with_opts::<{name}<'b>>(opts, buf)"
        ));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        // root_as_*_unchecked (unsafe)
        self.gen_doc_lines(&[
            &format!("Assumes, without verification, that a buffer of bytes contains a {name} and returns it."),
            "# Safety",
            &format!("Callers must trust the given bytes do indeed contain a valid `{name}`."),
        ]);
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub unsafe fn root_as_{snake}_unchecked(buf: &[u8]) -> {name}<'_> {{"
        ));
        self.w.indent();
        if self.opts.rust_pluggable_buffer {
            self.w.line(&format!(
                "unsafe {{ {name}::init_from_buffer(buf, __flatc_rs_runtime::root_loc(buf)) }}"
            ));
        } else {
            self.w.line(&format!(
                "unsafe {{ ::flatbuffers::root_unchecked::<{name}>(buf) }}"
            ));
        }
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        self.gen_doc_lines(&[
            &format!("Assumes, without verification, that a buffer of bytes contains a size prefixed {name} and returns it."),
            "# Safety",
            &format!("Callers must trust the given bytes do indeed contain a valid size prefixed `{name}`."),
        ]);
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub unsafe fn size_prefixed_root_as_{snake}_unchecked(buf: &[u8]) -> {name}<'_> {{"
        ));
        self.w.indent();
        if self.opts.rust_pluggable_buffer {
            self.w.line(&format!(
                "unsafe {{ {name}::init_from_buffer(buf, __flatc_rs_runtime::size_prefixed_root_loc(buf)) }}"
            ));
        } else {
            self.w.line(&format!(
                "unsafe {{ ::flatbuffers::size_prefixed_root_unchecked::<{name}>(buf) }}"
            ));
        }
        self.w.dedent();
        self.w.line("}");

        // file_identifier functions
        if let Some(ref ident) = self.schema.file_ident {
            if !ident.is_empty() {
                self.w.blank();
                self.w.line(&format!(
                    "pub const {upper_snake}_IDENTIFIER: &str = \"{ident}\";"
                ));
                self.w.blank();
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn {snake}_buffer_has_identifier(buf: &[u8]) -> bool {{"
                ));
                self.w.indent();
                self.w.line(&format!(
                    "::flatbuffers::buffer_has_identifier(buf, {upper_snake}_IDENTIFIER, false)"
                ));
                self.w.dedent();
                self.w.line("}");
                self.w.blank();
                self.w.line("#[inline]");
                self.w.line(&format!(
                    "pub fn {snake}_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {{"
                ));
                self.w.indent();
                self.w.line(&format!(
                    "::flatbuffers::buffer_has_identifier(buf, {upper_snake}_IDENTIFIER, true)"
                ));
                self.w.dedent();
                self.w.line("}");
            }
        }

        if let Some(ref extension) = self.schema.file_ext {
            if !extension.is_empty() {
                self.w.blank();
                self.w.line(&format!(
                    "pub const {upper_snake}_EXTENSION: &str = \"{extension}\";"
                ));
            }
        }

        let identifier = self
            .schema
            .file_ident
            .as_deref()
            .filter(|identifier| !identifier.is_empty())
            .map(|_| format!("Some({upper_snake}_IDENTIFIER)"))
            .unwrap_or_else(|| "None".to_string());

        self.w.blank();
        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn finish_{snake}_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>("
        ));
        self.w.indent();
        self.w
            .line("fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,");
        self.w
            .line(&format!("root: ::flatbuffers::WIPOffset<{name}<'a>>"));
        self.w.dedent();
        self.w.line(") {");
        self.w.indent();
        self.w.line(&format!("fbb.finish(root, {identifier});"));
        self.w.dedent();
        self.w.line("}");
        self.w.blank();

        self.w.line("#[inline]");
        self.w.line(&format!(
            "pub fn finish_size_prefixed_{snake}_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>("
        ));
        self.w.indent();
        self.w
            .line("fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,");
        self.w
            .line(&format!("root: ::flatbuffers::WIPOffset<{name}<'a>>"));
        self.w.dedent();
        self.w.line(") {");
        self.w.indent();
        self.w
            .line(&format!("fbb.finish_size_prefixed(root, {identifier});"));
        self.w.dedent();
        self.w.line("}");
    }
}
