use flatc_rs_schema::resolved::ResolvedSchema;

use super::code_writer::CodeWriter;
use super::namespace_tree::{self, NamespaceNode, TypeEntry};
use super::ts_enum_gen;
use super::ts_struct_gen;
use super::ts_table_gen;
use super::TsCodeGenOptions;

/// Main TypeScript code generator.
pub struct TsGenerator<'a> {
    pub schema: &'a ResolvedSchema,
    pub w: CodeWriter,
    pub opts: &'a TsCodeGenOptions,
}

impl<'a> TsGenerator<'a> {
    pub fn new(schema: &'a ResolvedSchema, opts: &'a TsCodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            opts,
        }
    }

    /// Generate all TypeScript code and return the source string.
    pub fn generate(mut self) -> String {
        self.gen_header();
        self.gen_body();
        self.w.finish()
    }

    fn gen_header(&mut self) {
        self.w
            .line("// automatically generated by flatc-rs, do not modify");
        self.w.line("// @generated");
        self.w.blank();
        self.w.line(
            "/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */",
        );
        self.w.blank();
        self.w.line("import * as flatbuffers from 'flatbuffers';");
    }

    /// Group all types by namespace and emit them.
    fn gen_body(&mut self) {
        let root = namespace_tree::build_namespace_tree(self.schema, &self.opts.gen_only_files);

        // Emit root-level types
        if !root.types.is_empty() {
            self.w.blank();
            self.gen_types(&root.types);
        }

        // Emit child namespace modules
        for (name, child) in &root.children {
            self.gen_namespace_node(name, child);
        }
    }

    /// Recursively emit a namespace node as `export namespace` blocks.
    fn gen_namespace_node(&mut self, name: &str, node: &NamespaceNode) {
        self.w.blank();
        self.w.line(&format!("export namespace {name} {{"));
        self.w.indent();

        // Types at this namespace level
        if !node.types.is_empty() {
            self.w.blank();
            self.gen_types(&node.types);
        }

        // Child namespaces
        for (child_name, child_node) in &node.children {
            self.gen_namespace_node(child_name, child_node);
        }

        self.w.dedent();
        self.w.line(&format!("}} // {name}"));
    }

    fn gen_types(&mut self, entries: &[TypeEntry]) {
        let gen_object_api = self.opts.gen_object_api;
        for entry in entries {
            match entry {
                TypeEntry::Enum(idx) => {
                    ts_enum_gen::generate(&mut self.w, self.schema, *idx, gen_object_api);
                    self.w.blank();
                }
                TypeEntry::Struct(idx) => {
                    ts_struct_gen::generate(&mut self.w, self.schema, *idx, gen_object_api);
                    self.w.blank();
                }
                TypeEntry::Table(idx) => {
                    ts_table_gen::generate(&mut self.w, self.schema, *idx, self.opts);
                    self.w.blank();
                }
            }
        }
    }
}
