use std::collections::BTreeMap;

use flatc_rs_schema as schema;

use super::code_writer::CodeWriter;
use super::should_generate;
use super::ts_enum_gen;
use super::ts_struct_gen;
use super::ts_table_gen;
use super::TsCodeGenOptions;

/// Main TypeScript code generator.
pub struct TsGenerator<'a> {
    pub schema: &'a schema::Schema,
    pub w: CodeWriter,
    pub opts: &'a TsCodeGenOptions,
}

impl<'a> TsGenerator<'a> {
    pub fn new(schema: &'a schema::Schema, opts: &'a TsCodeGenOptions) -> Self {
        Self {
            schema,
            w: CodeWriter::new(),
            opts,
        }
    }

    /// Generate all TypeScript code and return the source string.
    pub fn generate(mut self) -> String {
        self.gen_header();
        self.gen_body();
        self.w.finish()
    }

    fn gen_header(&mut self) {
        self.w
            .line("// automatically generated by flatc-rs, do not modify");
        self.w.line("// @generated");
        self.w.blank();
        self.w.line(
            "/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */",
        );
        self.w.blank();
        self.w.line("import * as flatbuffers from 'flatbuffers';");
    }

    /// Group all types by namespace and emit them.
    fn gen_body(&mut self) {
        let mut root = NamespaceNode::new();

        let filter = &self.opts.gen_only_files;

        for (i, enum_def) in self.schema.enums.iter().enumerate() {
            if !should_generate(enum_def.declaration_file.as_deref(), filter) {
                continue;
            }
            let ns = namespace_str(enum_def.namespace.as_ref());
            let parts: Vec<&str> = if ns.is_empty() {
                vec![]
            } else {
                ns.split('.').collect()
            };
            root.insert(&parts, TypeEntry::Enum(i));
        }

        for (i, obj) in self.schema.objects.iter().enumerate() {
            if !should_generate(obj.declaration_file.as_deref(), filter) {
                continue;
            }
            let ns = namespace_str(obj.namespace.as_ref());
            let parts: Vec<&str> = if ns.is_empty() {
                vec![]
            } else {
                ns.split('.').collect()
            };
            let entry = if obj.is_struct == Some(true) {
                TypeEntry::Struct(i)
            } else {
                TypeEntry::Table(i)
            };
            root.insert(&parts, entry);
        }

        // Emit root-level types
        if !root.types.is_empty() {
            self.w.blank();
            self.gen_types(&root.types);
        }

        // Emit child namespace modules
        for (name, child) in &root.children {
            self.gen_namespace_node(name, child);
        }
    }

    /// Recursively emit a namespace node as `export namespace` blocks.
    fn gen_namespace_node(&mut self, name: &str, node: &NamespaceNode) {
        self.w.blank();
        self.w
            .line(&format!("export namespace {name} {{"));
        self.w.indent();

        // Types at this namespace level
        if !node.types.is_empty() {
            self.w.blank();
            self.gen_types(&node.types);
        }

        // Child namespaces
        for (child_name, child_node) in &node.children {
            self.gen_namespace_node(child_name, child_node);
        }

        self.w.dedent();
        self.w.line(&format!("}} // {name}"));
    }

    fn gen_types(&mut self, entries: &[TypeEntry]) {
        let gen_object_api = self.opts.gen_object_api;
        for entry in entries {
            match entry {
                TypeEntry::Enum(idx) => {
                    ts_enum_gen::generate(&mut self.w, self.schema, *idx, gen_object_api);
                    self.w.blank();
                }
                TypeEntry::Struct(idx) => {
                    ts_struct_gen::generate(&mut self.w, self.schema, *idx, gen_object_api);
                    self.w.blank();
                }
                TypeEntry::Table(idx) => {
                    ts_table_gen::generate(&mut self.w, self.schema, *idx, gen_object_api);
                    self.w.blank();
                }
            }
        }
    }
}

/// What kind of type an entry represents.
enum TypeEntry {
    Enum(usize),
    Struct(usize),
    Table(usize),
}

/// A tree node for grouping types by namespace hierarchy.
struct NamespaceNode {
    children: BTreeMap<String, NamespaceNode>,
    types: Vec<TypeEntry>,
}

impl NamespaceNode {
    fn new() -> Self {
        Self {
            children: BTreeMap::new(),
            types: Vec::new(),
        }
    }

    fn insert(&mut self, parts: &[&str], entry: TypeEntry) {
        if parts.is_empty() {
            self.types.push(entry);
        } else {
            self.children
                .entry(parts[0].to_string())
                .or_insert_with(NamespaceNode::new)
                .insert(&parts[1..], entry);
        }
    }
}

/// Extract namespace string from an optional Namespace message.
fn namespace_str(ns: Option<&schema::Namespace>) -> String {
    ns.and_then(|n| n.namespace.as_deref())
        .unwrap_or("")
        .to_string()
}
