[package]
name = "codegen-flatbuffers"
description = "FlatBuffers schema adapter for codegen-schema"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
codegen-core = { git = "https://github.com/shuozeli/codegen-infra.git", rev = "92fdb379bfb4598c889680935b9d055730c89dc2" }
codegen-schema = { git = "https://github.com/shuozeli/codegen-infra.git", rev = "92fdb379bfb4598c889680935b9d055730c89dc2" }
flatc-rs-schema = { path = "../schema" }
thiserror = "2"

[dev-dependencies]
flatc-rs-schema = { path = "../schema" }
