// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod xlqy_3 {
    extern crate alloc;

    #[allow(unused_imports, dead_code)]
    pub mod parity {
        extern crate alloc;

        #[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
        pub const ENUM_MIN_PAYLOAD_KIND: u8 = 0;

        #[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
        pub const ENUM_MAX_PAYLOAD_KIND: u8 = 1;

        #[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_PAYLOAD_KIND: [PayloadKind; 2] = [
            PayloadKind::Unknown,
            PayloadKind::Item2,
        ];

        /// A compact schema covering Rust source parity-sensitive constructs.
        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct PayloadKind(pub u8);

        #[allow(non_upper_case_globals)]
        impl PayloadKind {
            pub const Unknown: Self = Self(0);
            pub const Item2: Self = Self(1);

            pub const ENUM_MIN: u8 = 0;
            pub const ENUM_MAX: u8 = 1;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::Unknown,
                Self::Item2,
            ];

            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Unknown => Some("Unknown"),
                    Self::Item2 => Some("Item2"),
                    _ => None,
                }
            }
        }

        impl ::core::fmt::Debug for PayloadKind {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }

        impl<'a> ::flatbuffers::Follow<'a> for PayloadKind {
            type Inner = Self;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for PayloadKind {
            type Output = PayloadKind;

            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for PayloadKind {
            type Scalar = u8;

            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }

            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for PayloadKind {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier, pos: usize
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for PayloadKind {}

        #[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
        pub const ENUM_MIN_PAYLOAD: u8 = 0;

        #[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
        pub const ENUM_MAX_PAYLOAD: u8 = 1;

        #[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_PAYLOAD: [Payload; 2] = [
            Payload::NONE,
            Payload::Sword,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct Payload(pub u8);

        #[allow(non_upper_case_globals)]
        impl Payload {
            pub const NONE: Self = Self(0);
            pub const Sword: Self = Self(1);

            pub const ENUM_MIN: u8 = 0;
            pub const ENUM_MAX: u8 = 1;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::NONE,
                Self::Sword,
            ];

            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::NONE => Some("NONE"),
                    Self::Sword => Some("Sword"),
                    _ => None,
                }
            }
        }

        impl ::core::fmt::Debug for Payload {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }

        impl<'a> ::flatbuffers::Follow<'a> for Payload {
            type Inner = Self;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for Payload {
            type Output = Payload;

            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for Payload {
            type Scalar = u8;

            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }

            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Payload {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier, pos: usize
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Payload {}

        pub struct PayloadUnionTableOffset {}

        // struct Vec3, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Vec3(pub [u8; 8]);

        impl Default for Vec3 {
            fn default() -> Self {
                Self([0; 8])
            }
        }

        impl ::core::fmt::Debug for Vec3 {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Vec3")
                    .field("type_", &self.type_())
                    .field("item0", &self.item0())
                    .field("kind", &self.kind())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Vec3 {}

        impl<'a> ::flatbuffers::Follow<'a> for Vec3 {
            type Inner = &'a Vec3;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Vec3>::follow(buf, loc) }
            }
        }

        impl<'a> ::flatbuffers::Follow<'a> for &'a Vec3 {
            type Inner = &'a Vec3;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Vec3>(buf, loc) }
            }
        }

        impl<'b> ::flatbuffers::Push for Vec3 {
            type Output = Vec3;

            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe { ::core::slice::from_raw_parts(self as *const Vec3 as *const u8, <Self as ::flatbuffers::Push>::size()) };
                dst.copy_from_slice(src);
            }

            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Vec3 {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier, pos: usize
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Vec3 {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                type_: f32,
                item0: u16,
                kind: PayloadKind,
            ) -> Self {
                let mut s = Self([0; 8]);
                s.set_type_(type_);
                s.set_item0(item0);
                s.set_kind(kind);
                s
            }

            pub fn type_(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_type_(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn item0(&self) -> u16 {
                let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_item0(&mut self, x: u16) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn kind(&self) -> PayloadKind {
                let mut mem = ::core::mem::MaybeUninit::<<PayloadKind as ::flatbuffers::EndianScalar>::Scalar>::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[6..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<PayloadKind as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_kind(&mut self, x: PayloadKind) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[6..].as_mut_ptr(),
                        ::core::mem::size_of::<<PayloadKind as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

        }

        // struct ArrayHolder, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ArrayHolder(pub [u8; 16]);

        impl Default for ArrayHolder {
            fn default() -> Self {
                Self([0; 16])
            }
        }

        impl ::core::fmt::Debug for ArrayHolder {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ArrayHolder")
                    .field("values", &self.values())
                    .field("kinds", &self.kinds())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ArrayHolder {}

        impl<'a> ::flatbuffers::Follow<'a> for ArrayHolder {
            type Inner = &'a ArrayHolder;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ArrayHolder>::follow(buf, loc) }
            }
        }

        impl<'a> ::flatbuffers::Follow<'a> for &'a ArrayHolder {
            type Inner = &'a ArrayHolder;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ArrayHolder>(buf, loc) }
            }
        }

        impl<'b> ::flatbuffers::Push for ArrayHolder {
            type Output = ArrayHolder;

            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe { ::core::slice::from_raw_parts(self as *const ArrayHolder as *const u8, <Self as ::flatbuffers::Push>::size()) };
                dst.copy_from_slice(src);
            }

            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ArrayHolder {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier, pos: usize
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ArrayHolder {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                values: &[i32; 3],
                kinds: &[PayloadKind; 2],
            ) -> Self {
                let mut s = Self([0; 16]);
                s.set_values(values);
                s.set_kinds(kinds);
                s
            }

            pub fn values(&'a self) -> ::flatbuffers::Array<'a, i32, 3> {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid array in this slot
                use ::flatbuffers::Follow;
                unsafe { ::flatbuffers::Array::follow(&self.0, 0) }
            }

            pub fn set_values(&mut self, items: &[i32; 3]) {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid array in this slot
                unsafe { ::flatbuffers::emplace_scalar_array(&mut self.0, 0, items) };
            }

            pub fn kinds(&'a self) -> ::flatbuffers::Array<'a, PayloadKind, 2> {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid array in this slot
                use ::flatbuffers::Follow;
                unsafe { ::flatbuffers::Array::follow(&self.0, 12) }
            }

            pub fn set_kinds(&mut self, x: &[PayloadKind; 2]) {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid array in this slot
                unsafe {
                    ::core::ptr::copy(
                        x.as_ptr() as *const u8,
                        self.0.as_mut_ptr().add(12),
                        2,
                    );
                }
            }

        }

        pub enum SwordOffset {}

        #[derive(Copy, Clone, PartialEq)]
        pub struct Sword<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Sword<'a> {
            type Inner = Sword<'a>;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> Sword<'a> {
            pub const VT_DAMAGE: ::flatbuffers::VOffsetT = 4;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Sword { _tab: table }
            }

            #[allow(unused_mut)]
            pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args SwordArgs
            ) -> ::flatbuffers::WIPOffset<Sword<'bldr>> {
                let mut builder = SwordBuilder::new(_fbb);
                builder.add_damage(args.damage);
                builder.finish()
            }


            #[inline]
            pub fn damage(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i32>(Sword::VT_DAMAGE, Some(0)).unwrap()}
            }
        }

        impl ::flatbuffers::Verifiable for Sword<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier, pos: usize
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<i32>("damage", Self::VT_DAMAGE, false)?
                    .finish();
                Ok(())
            }
        }

        pub struct SwordArgs {
            pub damage: i32,
        }

        impl<'a> Default for SwordArgs {
            #[inline]
            fn default() -> Self {
                SwordArgs {
                    damage: 0,
                }
            }
        }

        pub struct SwordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }

        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SwordBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_damage(&mut self, damage: i32) {
                self.fbb_.push_slot::<i32>(Sword::VT_DAMAGE, damage, 0);
            }

            #[inline]
            pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SwordBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                SwordBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }

            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Sword<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Sword<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Sword");
                ds.field("damage", &self.damage());
                ds.finish()
            }
        }

        pub enum EnvelopeOffset {}

        #[derive(Copy, Clone, PartialEq)]
        pub struct Envelope<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Envelope<'a> {
            type Inner = Envelope<'a>;

            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> Envelope<'a> {
            pub const VT_TYPE_: ::flatbuffers::VOffsetT = 4;
            pub const VT_ITEM0: ::flatbuffers::VOffsetT = 6;
            pub const VT_POSITION: ::flatbuffers::VOffsetT = 8;
            pub const VT_ARRAYS: ::flatbuffers::VOffsetT = 10;
            pub const VT_VALUES: ::flatbuffers::VOffsetT = 12;
            pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 14;
            pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 16;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Envelope { _tab: table }
            }

            #[allow(unused_mut)]
            pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args EnvelopeArgs<'args>
            ) -> ::flatbuffers::WIPOffset<Envelope<'bldr>> {
                let mut builder = EnvelopeBuilder::new(_fbb);
                if let Some(x) = args.payload { builder.add_payload(x); }
                if let Some(x) = args.values { builder.add_values(x); }
                if let Some(x) = args.arrays { builder.add_arrays(x); }
                if let Some(x) = args.position { builder.add_position(x); }
                if let Some(x) = args.item0 { builder.add_item0(x); }
                builder.add_type_(args.type_);
                builder.add_payload_type(args.payload_type);
                builder.finish()
            }


            #[inline]
            pub fn type_(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i32>(Envelope::VT_TYPE_, Some(0)).unwrap()}
            }

            #[inline]
            pub fn item0(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Envelope::VT_ITEM0, None)}
            }

            #[inline]
            pub fn position(&self) -> Option<&'a Vec3> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Vec3>(Envelope::VT_POSITION, None)}
            }

            #[inline]
            pub fn arrays(&self) -> Option<&'a ArrayHolder> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<ArrayHolder>(Envelope::VT_ARRAYS, None)}
            }

            #[inline]
            pub fn values(&self) -> Option<::flatbuffers::Vector<'a, i32>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i32>>>(Envelope::VT_VALUES, None)}
            }

            #[inline]
            pub fn payload_type(&self) -> Payload {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Payload>(Envelope::VT_PAYLOAD_TYPE, Some(Payload::NONE)).unwrap()}
            }

            #[inline]
            pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Envelope::VT_PAYLOAD, None)}
            }

            #[inline]
            #[allow(non_snake_case)]
            pub fn payload_as_sword(&self) -> Option<Sword<'a>> {
                if self.payload_type() == Payload::Sword {
                    self.payload().map(|t| {
                        // Safety:
                        // Created from a valid Table for this object
                        // Which contains a valid union in this slot
                        unsafe { Sword::init_from_table(t) }
                    })
                } else {
                    None
                }
            }
        }

        impl ::flatbuffers::Verifiable for Envelope<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier, pos: usize
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<i32>("type_", Self::VT_TYPE_, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("item0", Self::VT_ITEM0, false)?
                    .visit_field::<Vec3>("position", Self::VT_POSITION, false)?
                    .visit_field::<ArrayHolder>("arrays", Self::VT_ARRAYS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i32>>>("values", Self::VT_VALUES, false)?
                    .visit_union::<Payload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
                        match key {
                            Payload::Sword => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Sword>>("Payload::Sword", pos),
                            _ => Ok(()),
                        }
                    })?
                    .finish();
                Ok(())
            }
        }

        pub struct EnvelopeArgs<'a> {
            pub type_: i32,
            pub item0: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub position: Option<&'a Vec3>,
            pub arrays: Option<&'a ArrayHolder>,
            pub values: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i32>>>,
            pub payload_type: Payload,
            pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
        }

        impl<'a> Default for EnvelopeArgs<'a> {
            #[inline]
            fn default() -> Self {
                EnvelopeArgs {
                    type_: 0,
                    item0: None,
                    position: None,
                    arrays: None,
                    values: None,
                    payload_type: Payload::NONE,
                    payload: None,
                }
            }
        }

        pub struct EnvelopeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }

        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EnvelopeBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_type_(&mut self, type_: i32) {
                self.fbb_.push_slot::<i32>(Envelope::VT_TYPE_, type_, 0);
            }

            #[inline]
            pub fn add_item0(&mut self, item0: ::flatbuffers::WIPOffset<&'b  str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Envelope::VT_ITEM0, item0);
            }

            #[inline]
            pub fn add_position(&mut self, position: &Vec3) {
                self.fbb_.push_slot_always::<&Vec3>(Envelope::VT_POSITION, position);
            }

            #[inline]
            pub fn add_arrays(&mut self, arrays: &ArrayHolder) {
                self.fbb_.push_slot_always::<&ArrayHolder>(Envelope::VT_ARRAYS, arrays);
            }

            #[inline]
            pub fn add_values(&mut self, values: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i32>>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Envelope::VT_VALUES, values);
            }

            #[inline]
            pub fn add_payload_type(&mut self, payload_type: Payload) {
                self.fbb_.push_slot::<Payload>(Envelope::VT_PAYLOAD_TYPE, payload_type, Payload::NONE);
            }

            #[inline]
            pub fn add_payload(&mut self, payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Envelope::VT_PAYLOAD, payload);
            }

            #[inline]
            pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EnvelopeBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                EnvelopeBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }

            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Envelope<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Envelope<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Envelope");
                ds.field("type_", &self.type_());
                ds.field("item0", &self.item0());
                ds.field("position", &self.position());
                ds.field("arrays", &self.arrays());
                ds.field("values", &self.values());
                ds.field("payload_type", &self.payload_type());
                match self.payload_type() {
                    Payload::Sword => {
                        if let Some(x) = self.payload_as_sword() {
                            ds.field("payload", &x)
                        } else {
                            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
                        }
                    },
                    _ => {
                        let x: Option<()> = None;
                        ds.field("payload", &x)
                    },
                };
                ds.finish()
            }
        }

        /// Verifies that a buffer of bytes contains a `Envelope`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_envelope_unchecked`.
        #[inline]
        pub fn root_as_envelope(buf: &[u8]) -> Result<Envelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<Envelope>(buf)
        }

        /// Verifies that a buffer of bytes contains a size prefixed
        /// `Envelope` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_envelope_unchecked`.
        #[inline]
        pub fn size_prefixed_root_as_envelope(buf: &[u8]) -> Result<Envelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<Envelope>(buf)
        }

        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `Envelope` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_envelope_unchecked`.
        #[inline]
        pub fn root_as_envelope_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Envelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<Envelope<'b>>(opts, buf)
        }

        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `Envelope` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_envelope_unchecked`.
        #[inline]
        pub fn size_prefixed_root_as_envelope_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Envelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<Envelope<'b>>(opts, buf)
        }

        /// Assumes, without verification, that a buffer of bytes contains a Envelope and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `Envelope`.
        #[inline]
        pub unsafe fn root_as_envelope_unchecked(buf: &[u8]) -> Envelope<'_> {
            unsafe { ::flatbuffers::root_unchecked::<Envelope>(buf) }
        }

        /// Assumes, without verification, that a buffer of bytes contains a size prefixed Envelope and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `Envelope`.
        #[inline]
        pub unsafe fn size_prefixed_root_as_envelope_unchecked(buf: &[u8]) -> Envelope<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Envelope>(buf) }
        }

        pub const ENVELOPE_IDENTIFIER: &str = "PRTY";

        #[inline]
        pub fn envelope_buffer_has_identifier(buf: &[u8]) -> bool {
            ::flatbuffers::buffer_has_identifier(buf, ENVELOPE_IDENTIFIER, false)
        }

        #[inline]
        pub fn envelope_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
            ::flatbuffers::buffer_has_identifier(buf, ENVELOPE_IDENTIFIER, true)
        }

        #[inline]
        pub fn finish_envelope_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<Envelope<'a>>
        ) {
            fbb.finish(root, Some(ENVELOPE_IDENTIFIER));
        }

        #[inline]
        pub fn finish_size_prefixed_envelope_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<Envelope<'a>>
        ) {
            fbb.finish_size_prefixed(root, Some(ENVELOPE_IDENTIFIER));
        }
    } // pub mod parity
} // pub mod xlqy3
