// automatically generated by flatc-rs, do not modify
// @generated

extern crate alloc;
use self::flatbuffers::Follow;

pub enum TableAOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct TableA<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for TableA<'a> {
  type Inner = TableA<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TableA<'a> {
  pub const VT_B: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub const fn get_fully_qualified_name() -> &'static str {
    "TableA"
  }

  /// # Safety
  /// Caller must ensure the table is a valid instance of this type.
  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    TableA { _tab: table }
  }

  #[inline]
  pub fn b(&self) -> Option<TableB<'a>> {
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TableB>>(Self::VT_B, None) }
  }
}

impl ::flatbuffers::Verifiable for TableA<'_> {
  #[inline]
  fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
      .visit_field::<::flatbuffers::ForwardsUOffset<TableB<'_>>>("b", Self::VT_B, false)?
      .finish();
    Ok(())
  }
}

impl ::core::fmt::Debug for TableA<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("TableA");
    ds.field("b", &self.b());
    ds.finish()
  }
}

pub struct TableABuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TableABuilder<'a, 'b, A> {
  #[inline]
  pub fn add_b(&mut self, b: ::flatbuffers::WIPOffset<TableB<'b>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableA::VT_B, b);
  }

  #[inline]
  pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TableABuilder<'a, 'b, A> {
    let start = fbb.start_table();
    TableABuilder { fbb_: fbb, start_: start }
  }

  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<TableA<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

pub struct TableAArgs<'a> {
  pub b: Option<::flatbuffers::WIPOffset<TableB<'a>>>,
}

impl<'a> Default for TableAArgs<'a> {
  fn default() -> Self {
    TableAArgs {
      b: None,
    }
  }
}

#[inline]
pub fn createTableA<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
  fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
  args: &'args TableAArgs<'args>,
) -> ::flatbuffers::WIPOffset<TableA<'bldr>> {
  let mut builder = TableABuilder::new(fbb);
  if let Some(x) = args.b { builder.add_b(x); }
  builder.finish()
}


#[allow(unused_imports, dead_code)]
pub mod my_game {
  use super::*;

  #[allow(unused_imports, dead_code)]
  pub mod other_name_space {
    use super::*;

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct FromInclude(pub i64);

    #[allow(non_upper_case_globals)]
    impl FromInclude {
      pub const IncludeVal: Self = Self(0);

      pub const ENUM_MIN: i64 = 0;
      pub const ENUM_MAX: i64 = 0;
      pub const ENUM_VALUES: &'static [Self] = &[Self::IncludeVal];

      pub fn variant_name(self) -> Option<&'static str> {
        match self {
          Self::IncludeVal => Some("IncludeVal"),
          _ => None,
        }
      }
    }

    impl ::core::fmt::Debug for FromInclude {
      fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
          f.write_str(name)
        }
        else {
          f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
      }
    }

    impl<'a> ::flatbuffers::Follow<'a> for FromInclude {
      type Inner = Self;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<i64>(buf, loc) };
        Self(b)
      }
    }

    impl ::flatbuffers::Push for FromInclude {
      type Output = FromInclude;
      #[inline]
      unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i64>(dst, self.0) };
      }
    }

    impl ::flatbuffers::EndianScalar for FromInclude {
      type Scalar = i64;
      #[inline]
      fn to_little_endian(self) -> i64 {
        self.0.to_le()
      }
      #[inline]
      fn from_little_endian(v: i64) -> Self {
        let b = i64::from_le(v);
        Self(b)
      }
    }

    impl<'a> ::flatbuffers::Verifiable for FromInclude {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.in_buffer::<Self>(pos)
      }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for FromInclude {}

    // struct Unused, aligned to 4
    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq)]
    pub struct Unused(pub [u8; 4]);

    impl Default for Unused {
      fn default() -> Self {
        Self([0; 4])
      }
    }

    impl ::core::fmt::Debug for Unused {
      fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        f.debug_struct("Unused")
          .field("a", &self.a())
          .finish()
      }
    }

    impl Unused {
      pub fn new(a: i32) -> Self {
        let mut s = Self([0; 4]);
        s.set_a(a);
        s
      }

      pub fn a(&self) -> i32 {
        let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
        ::flatbuffers::EndianScalar::from_little_endian(unsafe {
          ::core::ptr::copy_nonoverlapping(
            self.0[0..].as_ptr(),
            mem.as_mut_ptr() as *mut u8,
            ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
          );
          mem.assume_init()
        })
      }

      pub fn set_a(&mut self, a: i32) {
        let a_le = ::flatbuffers::EndianScalar::to_little_endian(a);
        unsafe {
          ::core::ptr::copy_nonoverlapping(
            &a_le as *const _ as *const u8,
            self.0[0..].as_mut_ptr(),
            ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
          );
        }
      }

    }

    impl<'a> ::flatbuffers::Follow<'a> for Unused {
      type Inner = &'a Unused;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        unsafe { <&'a Unused>::follow(buf, loc) }
      }
    }

    impl<'a> ::flatbuffers::Follow<'a> for &'a Unused {
      type Inner = &'a Unused;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        unsafe { ::flatbuffers::follow_cast_ref::<Unused>(buf, loc) }
      }
    }

    impl<'b> ::flatbuffers::Push for Unused {
      type Output = Unused;
      #[inline]
      unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Unused as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
      }
      #[inline]
      fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
      }
    }

    impl<'a> ::flatbuffers::Verifiable for Unused {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.in_buffer::<Self>(pos)
      }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for Unused {}

    pub enum TableBOffset {}

    #[derive(Copy, Clone, PartialEq)]
    pub struct TableB<'a> {
      pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for TableB<'a> {
      type Inner = TableB<'a>;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
      }
    }

    impl<'a> TableB<'a> {
      pub const VT_A: ::flatbuffers::VOffsetT = 4;

      #[inline]
      pub const fn get_fully_qualified_name() -> &'static str {
        "MyGame.OtherNameSpace.TableB"
      }

      /// # Safety
      /// Caller must ensure the table is a valid instance of this type.
      #[inline]
      pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        TableB { _tab: table }
      }

      #[inline]
      pub fn a(&self) -> Option<TableA<'a>> {
        unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TableA>>(Self::VT_A, None) }
      }
    }

    impl ::flatbuffers::Verifiable for TableB<'_> {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
          .visit_field::<::flatbuffers::ForwardsUOffset<TableA<'_>>>("a", Self::VT_A, false)?
          .finish();
        Ok(())
      }
    }

    impl ::core::fmt::Debug for TableB<'_> {
      fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("TableB");
        ds.field("a", &self.a());
        ds.finish()
      }
    }

    pub struct TableBBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
      fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
      start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }

    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TableBBuilder<'a, 'b, A> {
      #[inline]
      pub fn add_a(&mut self, a: ::flatbuffers::WIPOffset<TableA<'b>>) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableB::VT_A, a);
      }

      #[inline]
      pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TableBBuilder<'a, 'b, A> {
        let start = fbb.start_table();
        TableBBuilder { fbb_: fbb, start_: start }
      }

      #[inline]
      pub fn finish(self) -> ::flatbuffers::WIPOffset<TableB<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
      }
    }

    pub struct TableBArgs<'a> {
      pub a: Option<::flatbuffers::WIPOffset<TableA<'a>>>,
    }

    impl<'a> Default for TableBArgs<'a> {
      fn default() -> Self {
        TableBArgs {
          a: None,
        }
      }
    }

    #[inline]
    pub fn createTableB<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
      fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
      args: &'args TableBArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<TableB<'bldr>> {
      let mut builder = TableBBuilder::new(fbb);
      if let Some(x) = args.a { builder.add_a(x); }
      builder.finish()
    }

  } // OtherNameSpace
} // MyGame
