// automatically generated by flatc-rs, do not modify
// @generated

extern crate alloc;
use self::flatbuffers::Follow;

#[allow(unused_imports, dead_code)]
pub mod keyword_test {
  use super::*;

  #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
  #[repr(transparent)]
  pub struct ABC(pub i32);

  #[allow(non_upper_case_globals)]
  impl ABC {
    pub const void: Self = Self(0);
    pub const where: Self = Self(1);
    pub const stackalloc: Self = Self(2);

    pub const ENUM_MIN: i32 = 0;
    pub const ENUM_MAX: i32 = 2;
    pub const ENUM_VALUES: &'static [Self] = &[Self::void, Self::where, Self::stackalloc];

    pub fn variant_name(self) -> Option<&'static str> {
      match self {
        Self::void => Some("void"),
        Self::where => Some("where"),
        Self::stackalloc => Some("stackalloc"),
        _ => None,
      }
    }
  }

  impl ::core::fmt::Debug for ABC {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
      if let Some(name) = self.variant_name() {
        f.write_str(name)
      }
      else {
        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
      }
    }
  }

  impl<'a> ::flatbuffers::Follow<'a> for ABC {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      let b = unsafe { ::flatbuffers::read_scalar_at::<i32>(buf, loc) };
      Self(b)
    }
  }

  impl ::flatbuffers::Push for ABC {
    type Output = ABC;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
      unsafe { ::flatbuffers::emplace_scalar::<i32>(dst, self.0) };
    }
  }

  impl ::flatbuffers::EndianScalar for ABC {
    type Scalar = i32;
    #[inline]
    fn to_little_endian(self) -> i32 {
      self.0.to_le()
    }
    #[inline]
    fn from_little_endian(v: i32) -> Self {
      let b = i32::from_le(v);
      Self(b)
    }
  }

  impl<'a> ::flatbuffers::Verifiable for ABC {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.in_buffer::<Self>(pos)
    }
  }

  impl ::flatbuffers::SimpleToVerifyInSlice for ABC {}

  #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
  #[repr(transparent)]
  pub struct public(pub i32);

  #[allow(non_upper_case_globals)]
  impl public {
    pub const : Self = Self(0);

    pub const ENUM_MIN: i32 = 0;
    pub const ENUM_MAX: i32 = 0;
    pub const ENUM_VALUES: &'static [Self] = &[Self::];

    pub fn variant_name(self) -> Option<&'static str> {
      match self {
        Self:: => Some(""),
        _ => None,
      }
    }
  }

  impl ::core::fmt::Debug for public {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
      if let Some(name) = self.variant_name() {
        f.write_str(name)
      }
      else {
        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
      }
    }
  }

  impl<'a> ::flatbuffers::Follow<'a> for public {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      let b = unsafe { ::flatbuffers::read_scalar_at::<i32>(buf, loc) };
      Self(b)
    }
  }

  impl ::flatbuffers::Push for public {
    type Output = public;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
      unsafe { ::flatbuffers::emplace_scalar::<i32>(dst, self.0) };
    }
  }

  impl ::flatbuffers::EndianScalar for public {
    type Scalar = i32;
    #[inline]
    fn to_little_endian(self) -> i32 {
      self.0.to_le()
    }
    #[inline]
    fn from_little_endian(v: i32) -> Self {
      let b = i32::from_le(v);
      Self(b)
    }
  }

  impl<'a> ::flatbuffers::Verifiable for public {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.in_buffer::<Self>(pos)
    }
  }

  impl ::flatbuffers::SimpleToVerifyInSlice for public {}

  #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
  #[repr(transparent)]
  pub struct KeywordsInUnion(pub u8);

  #[allow(non_upper_case_globals)]
  impl KeywordsInUnion {
    pub const NONE: Self = Self(0);
    pub const static: Self = Self(1);
    pub const internal: Self = Self(2);

    pub const ENUM_MIN: u8 = 0;
    pub const ENUM_MAX: u8 = 2;
    pub const ENUM_VALUES: &'static [Self] = &[Self::NONE, Self::static, Self::internal];

    pub fn variant_name(self) -> Option<&'static str> {
      match self {
        Self::NONE => Some("NONE"),
        Self::static => Some("static"),
        Self::internal => Some("internal"),
        _ => None,
      }
    }
  }

  impl ::core::fmt::Debug for KeywordsInUnion {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
      if let Some(name) = self.variant_name() {
        f.write_str(name)
      }
      else {
        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
      }
    }
  }

  impl<'a> ::flatbuffers::Follow<'a> for KeywordsInUnion {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
      Self(b)
    }
  }

  impl ::flatbuffers::Push for KeywordsInUnion {
    type Output = KeywordsInUnion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
      unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
  }

  impl ::flatbuffers::EndianScalar for KeywordsInUnion {
    type Scalar = u8;
    #[inline]
    fn to_little_endian(self) -> u8 {
      self.0.to_le()
    }
    #[inline]
    fn from_little_endian(v: u8) -> Self {
      let b = u8::from_le(v);
      Self(b)
    }
  }

  impl<'a> ::flatbuffers::Verifiable for KeywordsInUnion {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.in_buffer::<Self>(pos)
    }
  }

  impl ::flatbuffers::SimpleToVerifyInSlice for KeywordsInUnion {}

  pub struct KeywordsInUnionUnionTableOffset {}

  pub enum KeywordsInTableOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct KeywordsInTable<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for KeywordsInTable<'a> {
    type Inner = KeywordsInTable<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> KeywordsInTable<'a> {
    pub const VT_IS: ::flatbuffers::VOffsetT = 4;
    pub const VT_PRIVATE: ::flatbuffers::VOffsetT = 6;
    pub const VT_TYPE: ::flatbuffers::VOffsetT = 8;
    pub const VT_DEFAULT: ::flatbuffers::VOffsetT = 10;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "KeywordTest.KeywordsInTable"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      KeywordsInTable { _tab: table }
    }

    #[inline]
    pub fn is(&self) -> ABC {
      unsafe { self._tab.get::<ABC>(Self::VT_IS, Some(ABC::void)).unwrap() }
    }

    #[inline]
    pub fn private(&self) -> public {
      unsafe { self._tab.get::<public>(Self::VT_PRIVATE, Some(public(0))).unwrap() }
    }

    #[inline]
    pub fn type(&self) -> i32 {
      unsafe { self._tab.get::<i32>(Self::VT_TYPE, Some(0)).unwrap() }
    }

    #[inline]
    pub fn default(&self) -> bool {
      unsafe { self._tab.get::<bool>(Self::VT_DEFAULT, Some(false)).unwrap() }
    }
  }

  impl ::flatbuffers::Verifiable for KeywordsInTable<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<ABC>("is", Self::VT_IS, false)?
        .visit_field::<public>("private", Self::VT_PRIVATE, false)?
        .visit_field::<i32>("type", Self::VT_TYPE, false)?
        .visit_field::<bool>("default", Self::VT_DEFAULT, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for KeywordsInTable<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("KeywordsInTable");
      ds.field("is", &self.is());
      ds.field("private", &self.private());
      ds.field("type", &self.type());
      ds.field("default", &self.default());
      ds.finish()
    }
  }

  pub struct KeywordsInTableBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> KeywordsInTableBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_is(&mut self, is: ABC) {
      self.fbb_.push_slot::<ABC>(KeywordsInTable::VT_IS, is, ABC::void);
    }

    #[inline]
    pub fn add_private(&mut self, private: public) {
      self.fbb_.push_slot::<public>(KeywordsInTable::VT_PRIVATE, private, public(0));
    }

    #[inline]
    pub fn add_type(&mut self, type: i32) {
      self.fbb_.push_slot::<i32>(KeywordsInTable::VT_TYPE, type, 0);
    }

    #[inline]
    pub fn add_default(&mut self, default: bool) {
      self.fbb_.push_slot::<bool>(KeywordsInTable::VT_DEFAULT, default, false);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> KeywordsInTableBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      KeywordsInTableBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<KeywordsInTable<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct KeywordsInTableArgs {
    pub is: ABC,
    pub private: public,
    pub type: i32,
    pub default: bool,
  }

  impl Default for KeywordsInTableArgs {
    fn default() -> Self {
      KeywordsInTableArgs {
        is: ABC::void,
        private: public(0),
        type: 0,
        default: false,
      }
    }
  }

  #[inline]
  pub fn createKeywordsInTable<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KeywordsInTableArgs,
  ) -> ::flatbuffers::WIPOffset<KeywordsInTable<'bldr>> {
    let mut builder = KeywordsInTableBuilder::new(fbb);
    builder.add_is(args.is);
    builder.add_private(args.private);
    builder.add_type(args.type);
    builder.add_default(args.default);
    builder.finish()
  }

  pub enum Table2Offset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct Table2<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for Table2<'a> {
    type Inner = Table2<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> Table2<'a> {
    pub const VT_TYPE: ::flatbuffers::VOffsetT = 4;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "KeywordTest.Table2"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      Table2 { _tab: table }
    }

    #[inline]
    pub fn type(&self) -> Option<::flatbuffers::Table<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Self::VT_TYPE, None) }
    }

    #[inline]
    pub fn type_as_static(&self) -> Option<KeywordsInTable<'a>> {
      if self.type_type() == KeywordsInUnion::static {
        self.type().map(|t| unsafe { KeywordsInTable::init_from_table(t) })
      } else {
        None
      }
    }

    #[inline]
    pub fn type_as_internal(&self) -> Option<KeywordsInTable<'a>> {
      if self.type_type() == KeywordsInUnion::internal {
        self.type().map(|t| unsafe { KeywordsInTable::init_from_table(t) })
      } else {
        None
      }
    }
  }

  impl ::flatbuffers::Verifiable for Table2<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'_>>>("type", Self::VT_TYPE, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for Table2<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("Table2");
      ds.field("type", &self.type());
      ds.finish()
    }
  }

  pub struct Table2Builder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Table2Builder<'a, 'b, A> {
    #[inline]
    pub fn add_type(&mut self, type: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Table2::VT_TYPE, type);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> Table2Builder<'a, 'b, A> {
      let start = fbb.start_table();
      Table2Builder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<Table2<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct Table2Args<'a> {
    pub type: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
  }

  impl<'a> Default for Table2Args<'a> {
    fn default() -> Self {
      Table2Args {
        type: None,
      }
    }
  }

  #[inline]
  pub fn createTable2<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args Table2Args<'args>,
  ) -> ::flatbuffers::WIPOffset<Table2<'bldr>> {
    let mut builder = Table2Builder::new(fbb);
    if let Some(x) = args.type { builder.add_type(x); }
    builder.finish()
  }

} // KeywordTest
