// automatically generated by flatc-rs, do not modify
// @generated

extern crate alloc;
use self::flatbuffers::Follow;

#[allow(unused_imports, dead_code)]
pub mod namespace_a {
  use super::*;

  pub enum TableInFirstNSOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct TableInFirstNS<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for TableInFirstNS<'a> {
    type Inner = TableInFirstNS<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> TableInFirstNS<'a> {
    pub const VT_FOO_TABLE: ::flatbuffers::VOffsetT = 4;
    pub const VT_FOO_ENUM: ::flatbuffers::VOffsetT = 6;
    pub const VT_FOO_UNION: ::flatbuffers::VOffsetT = 8;
    pub const VT_FOO_STRUCT: ::flatbuffers::VOffsetT = 10;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "NamespaceA.TableInFirstNS"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      TableInFirstNS { _tab: table }
    }

    #[inline]
    pub fn foo_table(&self) -> Option<TableInNestedNS<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TableInNestedNS>>(Self::VT_FOO_TABLE, None) }
    }

    #[inline]
    pub fn foo_enum(&self) -> EnumInNestedNS {
      unsafe { self._tab.get::<EnumInNestedNS>(Self::VT_FOO_ENUM, Some(EnumInNestedNS(0))).unwrap() }
    }

    #[inline]
    pub fn foo_union(&self) -> Option<::flatbuffers::Table<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Self::VT_FOO_UNION, None) }
    }

    #[inline]
    pub fn foo_union_as_table_in_nested_ns(&self) -> Option<TableInNestedNS<'a>> {
      if self.foo_union_type() == UnionInNestedNS::TableInNestedNS {
        self.foo_union().map(|t| unsafe { TableInNestedNS::init_from_table(t) })
      } else {
        None
      }
    }

    #[inline]
    pub fn foo_struct(&self) -> Option<&'a StructInNestedNS> {
      unsafe { self._tab.get::<StructInNestedNS>(Self::VT_FOO_STRUCT, None) }
    }
  }

  impl ::flatbuffers::Verifiable for TableInFirstNS<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<::flatbuffers::ForwardsUOffset<TableInNestedNS<'_>>>("foo_table", Self::VT_FOO_TABLE, false)?
        .visit_field::<EnumInNestedNS>("foo_enum", Self::VT_FOO_ENUM, false)?
        .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'_>>>("foo_union", Self::VT_FOO_UNION, false)?
        .visit_field::<StructInNestedNS>("foo_struct", Self::VT_FOO_STRUCT, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for TableInFirstNS<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("TableInFirstNS");
      ds.field("foo_table", &self.foo_table());
      ds.field("foo_enum", &self.foo_enum());
      ds.field("foo_union", &self.foo_union());
      ds.field("foo_struct", &self.foo_struct());
      ds.finish()
    }
  }

  pub struct TableInFirstNSBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TableInFirstNSBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_foo_table(&mut self, foo_table: ::flatbuffers::WIPOffset<TableInNestedNS<'b>>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableInFirstNS::VT_FOO_TABLE, foo_table);
    }

    #[inline]
    pub fn add_foo_enum(&mut self, foo_enum: EnumInNestedNS) {
      self.fbb_.push_slot::<EnumInNestedNS>(TableInFirstNS::VT_FOO_ENUM, foo_enum, EnumInNestedNS(0));
    }

    #[inline]
    pub fn add_foo_union(&mut self, foo_union: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableInFirstNS::VT_FOO_UNION, foo_union);
    }

    #[inline]
    pub fn add_foo_struct(&mut self, foo_struct: &StructInNestedNS) {
      self.fbb_.push_slot_always::<&StructInNestedNS>(TableInFirstNS::VT_FOO_STRUCT, foo_struct);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TableInFirstNSBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      TableInFirstNSBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<TableInFirstNS<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct TableInFirstNSArgs<'a> {
    pub foo_table: Option<::flatbuffers::WIPOffset<TableInNestedNS<'a>>>,
    pub foo_enum: EnumInNestedNS,
    pub foo_union: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    pub foo_struct: Option<&'a StructInNestedNS>,
  }

  impl<'a> Default for TableInFirstNSArgs<'a> {
    fn default() -> Self {
      TableInFirstNSArgs {
        foo_table: None,
        foo_enum: EnumInNestedNS(0),
        foo_union: None,
        foo_struct: None,
      }
    }
  }

  #[inline]
  pub fn createTableInFirstNS<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TableInFirstNSArgs<'args>,
  ) -> ::flatbuffers::WIPOffset<TableInFirstNS<'bldr>> {
    let mut builder = TableInFirstNSBuilder::new(fbb);
    if let Some(x) = args.foo_table { builder.add_foo_table(x); }
    if let Some(x) = args.foo_union { builder.add_foo_union(x); }
    if let Some(x) = args.foo_struct { builder.add_foo_struct(x); }
    builder.add_foo_enum(args.foo_enum);
    builder.finish()
  }

  pub enum SecondTableInAOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct SecondTableInA<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for SecondTableInA<'a> {
    type Inner = SecondTableInA<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> SecondTableInA<'a> {
    pub const VT_REFER_TO_C: ::flatbuffers::VOffsetT = 4;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "NamespaceA.SecondTableInA"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      SecondTableInA { _tab: table }
    }

    #[inline]
    pub fn refer_to_c(&self) -> Option<TableInC<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TableInC>>(Self::VT_REFER_TO_C, None) }
    }
  }

  impl ::flatbuffers::Verifiable for SecondTableInA<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<::flatbuffers::ForwardsUOffset<TableInC<'_>>>("refer_to_c", Self::VT_REFER_TO_C, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for SecondTableInA<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("SecondTableInA");
      ds.field("refer_to_c", &self.refer_to_c());
      ds.finish()
    }
  }

  pub struct SecondTableInABuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SecondTableInABuilder<'a, 'b, A> {
    #[inline]
    pub fn add_refer_to_c(&mut self, refer_to_c: ::flatbuffers::WIPOffset<TableInC<'b>>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SecondTableInA::VT_REFER_TO_C, refer_to_c);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SecondTableInABuilder<'a, 'b, A> {
      let start = fbb.start_table();
      SecondTableInABuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<SecondTableInA<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct SecondTableInAArgs<'a> {
    pub refer_to_c: Option<::flatbuffers::WIPOffset<TableInC<'a>>>,
  }

  impl<'a> Default for SecondTableInAArgs<'a> {
    fn default() -> Self {
      SecondTableInAArgs {
        refer_to_c: None,
      }
    }
  }

  #[inline]
  pub fn createSecondTableInA<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SecondTableInAArgs<'args>,
  ) -> ::flatbuffers::WIPOffset<SecondTableInA<'bldr>> {
    let mut builder = SecondTableInABuilder::new(fbb);
    if let Some(x) = args.refer_to_c { builder.add_refer_to_c(x); }
    builder.finish()
  }


  #[allow(unused_imports, dead_code)]
  pub mod namespace_b {
    use super::*;

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct UnionInNestedNS(pub u8);

    #[allow(non_upper_case_globals)]
    impl UnionInNestedNS {
      pub const NONE: Self = Self(0);
      pub const TableInNestedNS: Self = Self(1);

      pub const ENUM_MIN: u8 = 0;
      pub const ENUM_MAX: u8 = 1;
      pub const ENUM_VALUES: &'static [Self] = &[Self::NONE, Self::TableInNestedNS];

      pub fn variant_name(self) -> Option<&'static str> {
        match self {
          Self::NONE => Some("NONE"),
          Self::TableInNestedNS => Some("TableInNestedNS"),
          _ => None,
        }
      }
    }

    impl ::core::fmt::Debug for UnionInNestedNS {
      fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
          f.write_str(name)
        }
        else {
          f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
      }
    }

    impl<'a> ::flatbuffers::Follow<'a> for UnionInNestedNS {
      type Inner = Self;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
        Self(b)
      }
    }

    impl ::flatbuffers::Push for UnionInNestedNS {
      type Output = UnionInNestedNS;
      #[inline]
      unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
      }
    }

    impl ::flatbuffers::EndianScalar for UnionInNestedNS {
      type Scalar = u8;
      #[inline]
      fn to_little_endian(self) -> u8 {
        self.0.to_le()
      }
      #[inline]
      fn from_little_endian(v: u8) -> Self {
        let b = u8::from_le(v);
        Self(b)
      }
    }

    impl<'a> ::flatbuffers::Verifiable for UnionInNestedNS {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.in_buffer::<Self>(pos)
      }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for UnionInNestedNS {}

    pub struct UnionInNestedNSUnionTableOffset {}

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct EnumInNestedNS(pub i8);

    #[allow(non_upper_case_globals)]
    impl EnumInNestedNS {
      pub const A: Self = Self(0);
      pub const B: Self = Self(1);
      pub const C: Self = Self(2);

      pub const ENUM_MIN: i8 = 0;
      pub const ENUM_MAX: i8 = 2;
      pub const ENUM_VALUES: &'static [Self] = &[Self::A, Self::B, Self::C];

      pub fn variant_name(self) -> Option<&'static str> {
        match self {
          Self::A => Some("A"),
          Self::B => Some("B"),
          Self::C => Some("C"),
          _ => None,
        }
      }
    }

    impl ::core::fmt::Debug for EnumInNestedNS {
      fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
          f.write_str(name)
        }
        else {
          f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
      }
    }

    impl<'a> ::flatbuffers::Follow<'a> for EnumInNestedNS {
      type Inner = Self;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
        Self(b)
      }
    }

    impl ::flatbuffers::Push for EnumInNestedNS {
      type Output = EnumInNestedNS;
      #[inline]
      unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
      }
    }

    impl ::flatbuffers::EndianScalar for EnumInNestedNS {
      type Scalar = i8;
      #[inline]
      fn to_little_endian(self) -> i8 {
        self.0.to_le()
      }
      #[inline]
      fn from_little_endian(v: i8) -> Self {
        let b = i8::from_le(v);
        Self(b)
      }
    }

    impl<'a> ::flatbuffers::Verifiable for EnumInNestedNS {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.in_buffer::<Self>(pos)
      }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for EnumInNestedNS {}

    pub enum TableInNestedNSOffset {}

    #[derive(Copy, Clone, PartialEq)]
    pub struct TableInNestedNS<'a> {
      pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for TableInNestedNS<'a> {
      type Inner = TableInNestedNS<'a>;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
      }
    }

    impl<'a> TableInNestedNS<'a> {
      pub const VT_FOO: ::flatbuffers::VOffsetT = 4;

      #[inline]
      pub const fn get_fully_qualified_name() -> &'static str {
        "NamespaceA.NamespaceB.TableInNestedNS"
      }

      /// # Safety
      /// Caller must ensure the table is a valid instance of this type.
      #[inline]
      pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        TableInNestedNS { _tab: table }
      }

      #[inline]
      pub fn foo(&self) -> i32 {
        unsafe { self._tab.get::<i32>(Self::VT_FOO, Some(0)).unwrap() }
      }
    }

    impl ::flatbuffers::Verifiable for TableInNestedNS<'_> {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
          .visit_field::<i32>("foo", Self::VT_FOO, false)?
          .finish();
        Ok(())
      }
    }

    impl ::core::fmt::Debug for TableInNestedNS<'_> {
      fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("TableInNestedNS");
        ds.field("foo", &self.foo());
        ds.finish()
      }
    }

    pub struct TableInNestedNSBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
      fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
      start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }

    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TableInNestedNSBuilder<'a, 'b, A> {
      #[inline]
      pub fn add_foo(&mut self, foo: i32) {
        self.fbb_.push_slot::<i32>(TableInNestedNS::VT_FOO, foo, 0);
      }

      #[inline]
      pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TableInNestedNSBuilder<'a, 'b, A> {
        let start = fbb.start_table();
        TableInNestedNSBuilder { fbb_: fbb, start_: start }
      }

      #[inline]
      pub fn finish(self) -> ::flatbuffers::WIPOffset<TableInNestedNS<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
      }
    }

    pub struct TableInNestedNSArgs {
      pub foo: i32,
    }

    impl Default for TableInNestedNSArgs {
      fn default() -> Self {
        TableInNestedNSArgs {
          foo: 0,
        }
      }
    }

    #[inline]
    pub fn createTableInNestedNS<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
      fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
      args: &'args TableInNestedNSArgs,
    ) -> ::flatbuffers::WIPOffset<TableInNestedNS<'bldr>> {
      let mut builder = TableInNestedNSBuilder::new(fbb);
      builder.add_foo(args.foo);
      builder.finish()
    }

    // struct StructInNestedNS, aligned to 4
    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq)]
    pub struct StructInNestedNS(pub [u8; 8]);

    impl Default for StructInNestedNS {
      fn default() -> Self {
        Self([0; 8])
      }
    }

    impl ::core::fmt::Debug for StructInNestedNS {
      fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        f.debug_struct("StructInNestedNS")
          .field("a", &self.a())
          .field("b", &self.b())
          .finish()
      }
    }

    impl StructInNestedNS {
      pub fn new(a: i32, b: i32) -> Self {
        let mut s = Self([0; 8]);
        s.set_a(a);
        s.set_b(b);
        s
      }

      pub fn a(&self) -> i32 {
        let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
        ::flatbuffers::EndianScalar::from_little_endian(unsafe {
          ::core::ptr::copy_nonoverlapping(
            self.0[0..].as_ptr(),
            mem.as_mut_ptr() as *mut u8,
            ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
          );
          mem.assume_init()
        })
      }

      pub fn set_a(&mut self, a: i32) {
        let a_le = ::flatbuffers::EndianScalar::to_little_endian(a);
        unsafe {
          ::core::ptr::copy_nonoverlapping(
            &a_le as *const _ as *const u8,
            self.0[0..].as_mut_ptr(),
            ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
          );
        }
      }

      pub fn b(&self) -> i32 {
        let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
        ::flatbuffers::EndianScalar::from_little_endian(unsafe {
          ::core::ptr::copy_nonoverlapping(
            self.0[4..].as_ptr(),
            mem.as_mut_ptr() as *mut u8,
            ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
          );
          mem.assume_init()
        })
      }

      pub fn set_b(&mut self, b: i32) {
        let b_le = ::flatbuffers::EndianScalar::to_little_endian(b);
        unsafe {
          ::core::ptr::copy_nonoverlapping(
            &b_le as *const _ as *const u8,
            self.0[4..].as_mut_ptr(),
            ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
          );
        }
      }

    }

    impl<'a> ::flatbuffers::Follow<'a> for StructInNestedNS {
      type Inner = &'a StructInNestedNS;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        unsafe { <&'a StructInNestedNS>::follow(buf, loc) }
      }
    }

    impl<'a> ::flatbuffers::Follow<'a> for &'a StructInNestedNS {
      type Inner = &'a StructInNestedNS;
      #[inline]
      unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        unsafe { ::flatbuffers::follow_cast_ref::<StructInNestedNS>(buf, loc) }
      }
    }

    impl<'b> ::flatbuffers::Push for StructInNestedNS {
      type Output = StructInNestedNS;
      #[inline]
      unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const StructInNestedNS as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
      }
      #[inline]
      fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
      }
    }

    impl<'a> ::flatbuffers::Verifiable for StructInNestedNS {
      #[inline]
      fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.in_buffer::<Self>(pos)
      }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for StructInNestedNS {}

  } // NamespaceB
} // NamespaceA

#[allow(unused_imports, dead_code)]
pub mod namespace_c {
  use super::*;

  pub enum TableInCOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct TableInC<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for TableInC<'a> {
    type Inner = TableInC<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> TableInC<'a> {
    pub const VT_REFER_TO_A1: ::flatbuffers::VOffsetT = 4;
    pub const VT_REFER_TO_A2: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "NamespaceC.TableInC"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      TableInC { _tab: table }
    }

    #[inline]
    pub fn refer_to_a1(&self) -> Option<TableInFirstNS<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TableInFirstNS>>(Self::VT_REFER_TO_A1, None) }
    }

    #[inline]
    pub fn refer_to_a2(&self) -> Option<SecondTableInA<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<SecondTableInA>>(Self::VT_REFER_TO_A2, None) }
    }
  }

  impl ::flatbuffers::Verifiable for TableInC<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<::flatbuffers::ForwardsUOffset<TableInFirstNS<'_>>>("refer_to_a1", Self::VT_REFER_TO_A1, false)?
        .visit_field::<::flatbuffers::ForwardsUOffset<SecondTableInA<'_>>>("refer_to_a2", Self::VT_REFER_TO_A2, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for TableInC<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("TableInC");
      ds.field("refer_to_a1", &self.refer_to_a1());
      ds.field("refer_to_a2", &self.refer_to_a2());
      ds.finish()
    }
  }

  pub struct TableInCBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TableInCBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_refer_to_a1(&mut self, refer_to_a1: ::flatbuffers::WIPOffset<TableInFirstNS<'b>>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableInC::VT_REFER_TO_A1, refer_to_a1);
    }

    #[inline]
    pub fn add_refer_to_a2(&mut self, refer_to_a2: ::flatbuffers::WIPOffset<SecondTableInA<'b>>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableInC::VT_REFER_TO_A2, refer_to_a2);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TableInCBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      TableInCBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<TableInC<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct TableInCArgs<'a> {
    pub refer_to_a1: Option<::flatbuffers::WIPOffset<TableInFirstNS<'a>>>,
    pub refer_to_a2: Option<::flatbuffers::WIPOffset<SecondTableInA<'a>>>,
  }

  impl<'a> Default for TableInCArgs<'a> {
    fn default() -> Self {
      TableInCArgs {
        refer_to_a1: None,
        refer_to_a2: None,
      }
    }
  }

  #[inline]
  pub fn createTableInC<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TableInCArgs<'args>,
  ) -> ::flatbuffers::WIPOffset<TableInC<'bldr>> {
    let mut builder = TableInCBuilder::new(fbb);
    if let Some(x) = args.refer_to_a1 { builder.add_refer_to_a1(x); }
    if let Some(x) = args.refer_to_a2 { builder.add_refer_to_a2(x); }
    builder.finish()
  }

} // NamespaceC
