// automatically generated by flatc-rs, do not modify
// @generated

extern crate alloc;
use self::flatbuffers::Follow;

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct AB(pub i8);

#[allow(non_upper_case_globals)]
impl AB {
  pub const A: Self = Self(0);
  pub const B: Self = Self(1);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[Self::A, Self::B];

  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::A => Some("A"),
      Self::B => Some("B"),
      _ => None,
    }
  }
}

impl ::core::fmt::Debug for AB {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    }
    else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}

impl<'a> ::flatbuffers::Follow<'a> for AB {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for AB {
  type Output = AB;
  #[inline]
  unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
    unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
  }
}

impl ::flatbuffers::EndianScalar for AB {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for AB {
  #[inline]
  fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for AB {}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Any(pub u8);

#[allow(non_upper_case_globals)]
impl Any {
  pub const NONE: Self = Self(0);
  pub const Game: Self = Self(1);
  pub const Annotations: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[Self::NONE, Self::Game, Self::Annotations];

  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Game => Some("Game"),
      Self::Annotations => Some("Annotations"),
      _ => None,
    }
  }
}

impl ::core::fmt::Debug for Any {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    }
    else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}

impl<'a> ::flatbuffers::Follow<'a> for Any {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Any {
  type Output = Any;
  #[inline]
  unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
    unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
  }
}

impl ::flatbuffers::EndianScalar for Any {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Any {
  #[inline]
  fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Any {}

pub struct AnyUnionTableOffset {}

// struct Object, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Object(pub [u8; 4]);

impl Default for Object {
  fn default() -> Self {
    Self([0; 4])
  }
}

impl ::core::fmt::Debug for Object {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Object")
      .field("value", &self.value())
      .finish()
  }
}

impl Object {
  pub fn new(value: i32) -> Self {
    let mut s = Self([0; 4]);
    s.set_value(value);
    s
  }

  pub fn value(&self) -> i32 {
    let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_value(&mut self, value: i32) {
    let value_le = ::flatbuffers::EndianScalar::to_little_endian(value);
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &value_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

impl<'a> ::flatbuffers::Follow<'a> for Object {
  type Inner = &'a Object;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Object>::follow(buf, loc) }
  }
}

impl<'a> ::flatbuffers::Follow<'a> for &'a Object {
  type Inner = &'a Object;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Object>(buf, loc) }
  }
}

impl<'b> ::flatbuffers::Push for Object {
  type Output = Object;
  #[inline]
  unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
    let src = unsafe { ::core::slice::from_raw_parts(self as *const Object as *const u8, <Self as ::flatbuffers::Push>::size()) };
    dst.copy_from_slice(src);
  }
  #[inline]
  fn alignment() -> ::flatbuffers::PushAlignment {
    ::flatbuffers::PushAlignment::new(4)
  }
}

impl<'a> ::flatbuffers::Verifiable for Object {
  #[inline]
  fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Object {}

pub enum GameOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct Game<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Game<'a> {
  type Inner = Game<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Game<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub const fn get_fully_qualified_name() -> &'static str {
    "Game"
  }

  /// # Safety
  /// Caller must ensure the table is a valid instance of this type.
  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Game { _tab: table }
  }

  #[inline]
  pub fn value(&self) -> i32 {
    unsafe { self._tab.get::<i32>(Self::VT_VALUE, Some(0)).unwrap() }
  }
}

impl ::flatbuffers::Verifiable for Game<'_> {
  #[inline]
  fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
      .visit_field::<i32>("value", Self::VT_VALUE, false)?
      .finish();
    Ok(())
  }
}

impl ::core::fmt::Debug for Game<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Game");
    ds.field("value", &self.value());
    ds.finish()
  }
}

pub struct GameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GameBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: i32) {
    self.fbb_.push_slot::<i32>(Game::VT_VALUE, value, 0);
  }

  #[inline]
  pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GameBuilder<'a, 'b, A> {
    let start = fbb.start_table();
    GameBuilder { fbb_: fbb, start_: start }
  }

  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Game<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

pub struct GameArgs {
  pub value: i32,
}

impl Default for GameArgs {
  fn default() -> Self {
    GameArgs {
      value: 0,
    }
  }
}

#[inline]
pub fn createGame<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
  fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
  args: &'args GameArgs,
) -> ::flatbuffers::WIPOffset<Game<'bldr>> {
  let mut builder = GameBuilder::new(fbb);
  builder.add_value(args.value);
  builder.finish()
}

pub enum AnnotationsOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct Annotations<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Annotations<'a> {
  type Inner = Annotations<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Annotations<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub const fn get_fully_qualified_name() -> &'static str {
    "Annotations"
  }

  /// # Safety
  /// Caller must ensure the table is a valid instance of this type.
  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Annotations { _tab: table }
  }

  #[inline]
  pub fn value(&self) -> i32 {
    unsafe { self._tab.get::<i32>(Self::VT_VALUE, Some(0)).unwrap() }
  }
}

impl ::flatbuffers::Verifiable for Annotations<'_> {
  #[inline]
  fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
      .visit_field::<i32>("value", Self::VT_VALUE, false)?
      .finish();
    Ok(())
  }
}

impl ::core::fmt::Debug for Annotations<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Annotations");
    ds.field("value", &self.value());
    ds.finish()
  }
}

pub struct AnnotationsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AnnotationsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: i32) {
    self.fbb_.push_slot::<i32>(Annotations::VT_VALUE, value, 0);
  }

  #[inline]
  pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AnnotationsBuilder<'a, 'b, A> {
    let start = fbb.start_table();
    AnnotationsBuilder { fbb_: fbb, start_: start }
  }

  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Annotations<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

pub struct AnnotationsArgs {
  pub value: i32,
}

impl Default for AnnotationsArgs {
  fn default() -> Self {
    AnnotationsArgs {
      value: 0,
    }
  }
}

#[inline]
pub fn createAnnotations<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
  fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
  args: &'args AnnotationsArgs,
) -> ::flatbuffers::WIPOffset<Annotations<'bldr>> {
  let mut builder = AnnotationsBuilder::new(fbb);
  builder.add_value(args.value);
  builder.finish()
}

