// automatically generated by flatc-rs, do not modify
// @generated

extern crate alloc;
use self::flatbuffers::Follow;

#[allow(unused_imports, dead_code)]
pub mod rust_namer_test {
  use super::*;

  #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
  #[repr(transparent)]
  pub struct FieldUnion(pub u8);

  #[allow(non_upper_case_globals)]
  impl FieldUnion {
    pub const NONE: Self = Self(0);
    pub const f: Self = Self(1);

    pub const ENUM_MIN: u8 = 0;
    pub const ENUM_MAX: u8 = 1;
    pub const ENUM_VALUES: &'static [Self] = &[Self::NONE, Self::f];

    pub fn variant_name(self) -> Option<&'static str> {
      match self {
        Self::NONE => Some("NONE"),
        Self::f => Some("f"),
        _ => None,
      }
    }
  }

  impl ::core::fmt::Debug for FieldUnion {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
      if let Some(name) = self.variant_name() {
        f.write_str(name)
      }
      else {
        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
      }
    }
  }

  impl<'a> ::flatbuffers::Follow<'a> for FieldUnion {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
      Self(b)
    }
  }

  impl ::flatbuffers::Push for FieldUnion {
    type Output = FieldUnion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
      unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
  }

  impl ::flatbuffers::EndianScalar for FieldUnion {
    type Scalar = u8;
    #[inline]
    fn to_little_endian(self) -> u8 {
      self.0.to_le()
    }
    #[inline]
    fn from_little_endian(v: u8) -> Self {
      let b = u8::from_le(v);
      Self(b)
    }
  }

  impl<'a> ::flatbuffers::Verifiable for FieldUnion {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.in_buffer::<Self>(pos)
    }
  }

  impl ::flatbuffers::SimpleToVerifyInSlice for FieldUnion {}

  pub struct FieldUnionUnionTableOffset {}

  #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
  #[repr(transparent)]
  pub struct GameMessage(pub u8);

  #[allow(non_upper_case_globals)]
  impl GameMessage {
    pub const NONE: Self = Self(0);
    pub const PlayerStatEvent: Self = Self(1);
    pub const PlayerSpectate: Self = Self(2);
    pub const PlayerInputChange: Self = Self(3);

    pub const ENUM_MIN: u8 = 0;
    pub const ENUM_MAX: u8 = 3;
    pub const ENUM_VALUES: &'static [Self] = &[Self::NONE, Self::PlayerStatEvent, Self::PlayerSpectate, Self::PlayerInputChange];

    pub fn variant_name(self) -> Option<&'static str> {
      match self {
        Self::NONE => Some("NONE"),
        Self::PlayerStatEvent => Some("PlayerStatEvent"),
        Self::PlayerSpectate => Some("PlayerSpectate"),
        Self::PlayerInputChange => Some("PlayerInputChange"),
        _ => None,
      }
    }
  }

  impl ::core::fmt::Debug for GameMessage {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
      if let Some(name) = self.variant_name() {
        f.write_str(name)
      }
      else {
        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
      }
    }
  }

  impl<'a> ::flatbuffers::Follow<'a> for GameMessage {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
      Self(b)
    }
  }

  impl ::flatbuffers::Push for GameMessage {
    type Output = GameMessage;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
      unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
  }

  impl ::flatbuffers::EndianScalar for GameMessage {
    type Scalar = u8;
    #[inline]
    fn to_little_endian(self) -> u8 {
      self.0.to_le()
    }
    #[inline]
    fn from_little_endian(v: u8) -> Self {
      let b = u8::from_le(v);
      Self(b)
    }
  }

  impl<'a> ::flatbuffers::Verifiable for GameMessage {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.in_buffer::<Self>(pos)
    }
  }

  impl ::flatbuffers::SimpleToVerifyInSlice for GameMessage {}

  pub struct GameMessageUnionTableOffset {}

  pub enum FieldTableOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct FieldTable<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for FieldTable<'a> {
    type Inner = FieldTable<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> FieldTable<'a> {

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "RustNamerTest.FieldTable"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      FieldTable { _tab: table }
    }
  }

  impl ::flatbuffers::Verifiable for FieldTable<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for FieldTable<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("FieldTable");
      ds.finish()
    }
  }

  pub struct FieldTableBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FieldTableBuilder<'a, 'b, A> {
    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FieldTableBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      FieldTableBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<FieldTable<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct FieldTableArgs {
  }

  impl Default for FieldTableArgs {
    fn default() -> Self {
      FieldTableArgs {
      }
    }
  }

  #[inline]
  pub fn createFieldTable<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FieldTableArgs,
  ) -> ::flatbuffers::WIPOffset<FieldTable<'bldr>> {
    let mut builder = FieldTableBuilder::new(fbb);
    builder.finish()
  }

  pub enum RootTableOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct RootTable<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for RootTable<'a> {
    type Inner = RootTable<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> RootTable<'a> {
    pub const VT_FIELD42: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "RustNamerTest.RootTable"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      RootTable { _tab: table }
    }

    #[inline]
    pub fn field42(&self) -> Option<::flatbuffers::Table<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Self::VT_FIELD42, None) }
    }

    #[inline]
    pub fn field42_as_f(&self) -> Option<FieldTable<'a>> {
      if self.field42_type() == FieldUnion::f {
        self.field42().map(|t| unsafe { FieldTable::init_from_table(t) })
      } else {
        None
      }
    }
  }

  impl ::flatbuffers::Verifiable for RootTable<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'_>>>("field42", Self::VT_FIELD42, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for RootTable<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("RootTable");
      ds.field("field42", &self.field42());
      ds.finish()
    }
  }

  pub struct RootTableBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RootTableBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_field42(&mut self, field42: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RootTable::VT_FIELD42, field42);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RootTableBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      RootTableBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<RootTable<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct RootTableArgs<'a> {
    pub field42: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
  }

  impl<'a> Default for RootTableArgs<'a> {
    fn default() -> Self {
      RootTableArgs {
        field42: None,
      }
    }
  }

  #[inline]
  pub fn createRootTable<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RootTableArgs<'args>,
  ) -> ::flatbuffers::WIPOffset<RootTable<'bldr>> {
    let mut builder = RootTableBuilder::new(fbb);
    if let Some(x) = args.field42 { builder.add_field42(x); }
    builder.finish()
  }

  pub enum PlayerStatEventOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct PlayerStatEvent<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for PlayerStatEvent<'a> {
    type Inner = PlayerStatEvent<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> PlayerStatEvent<'a> {

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "RustNamerTest.PlayerStatEvent"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      PlayerStatEvent { _tab: table }
    }
  }

  impl ::flatbuffers::Verifiable for PlayerStatEvent<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for PlayerStatEvent<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("PlayerStatEvent");
      ds.finish()
    }
  }

  pub struct PlayerStatEventBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerStatEventBuilder<'a, 'b, A> {
    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerStatEventBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      PlayerStatEventBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerStatEvent<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct PlayerStatEventArgs {
  }

  impl Default for PlayerStatEventArgs {
    fn default() -> Self {
      PlayerStatEventArgs {
      }
    }
  }

  #[inline]
  pub fn createPlayerStatEvent<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PlayerStatEventArgs,
  ) -> ::flatbuffers::WIPOffset<PlayerStatEvent<'bldr>> {
    let mut builder = PlayerStatEventBuilder::new(fbb);
    builder.finish()
  }

  pub enum PlayerSpectateOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct PlayerSpectate<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for PlayerSpectate<'a> {
    type Inner = PlayerSpectate<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> PlayerSpectate<'a> {

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "RustNamerTest.PlayerSpectate"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      PlayerSpectate { _tab: table }
    }
  }

  impl ::flatbuffers::Verifiable for PlayerSpectate<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for PlayerSpectate<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("PlayerSpectate");
      ds.finish()
    }
  }

  pub struct PlayerSpectateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerSpectateBuilder<'a, 'b, A> {
    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerSpectateBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      PlayerSpectateBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerSpectate<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct PlayerSpectateArgs {
  }

  impl Default for PlayerSpectateArgs {
    fn default() -> Self {
      PlayerSpectateArgs {
      }
    }
  }

  #[inline]
  pub fn createPlayerSpectate<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PlayerSpectateArgs,
  ) -> ::flatbuffers::WIPOffset<PlayerSpectate<'bldr>> {
    let mut builder = PlayerSpectateBuilder::new(fbb);
    builder.finish()
  }

  pub enum PlayerInputChangeOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct PlayerInputChange<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for PlayerInputChange<'a> {
    type Inner = PlayerInputChange<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> PlayerInputChange<'a> {

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "RustNamerTest.PlayerInputChange"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      PlayerInputChange { _tab: table }
    }
  }

  impl ::flatbuffers::Verifiable for PlayerInputChange<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for PlayerInputChange<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("PlayerInputChange");
      ds.finish()
    }
  }

  pub struct PlayerInputChangeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerInputChangeBuilder<'a, 'b, A> {
    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerInputChangeBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      PlayerInputChangeBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerInputChange<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct PlayerInputChangeArgs {
  }

  impl Default for PlayerInputChangeArgs {
    fn default() -> Self {
      PlayerInputChangeArgs {
      }
    }
  }

  #[inline]
  pub fn createPlayerInputChange<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PlayerInputChangeArgs,
  ) -> ::flatbuffers::WIPOffset<PlayerInputChange<'bldr>> {
    let mut builder = PlayerInputChangeBuilder::new(fbb);
    builder.finish()
  }

  pub enum GameMessageWrapperOffset {}

  #[derive(Copy, Clone, PartialEq)]
  pub struct GameMessageWrapper<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
  }

  impl<'a> ::flatbuffers::Follow<'a> for GameMessageWrapper<'a> {
    type Inner = GameMessageWrapper<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
  }

  impl<'a> GameMessageWrapper<'a> {
    pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 4;

    #[inline]
    pub const fn get_fully_qualified_name() -> &'static str {
      "RustNamerTest.GameMessageWrapper"
    }

    /// # Safety
    /// Caller must ensure the table is a valid instance of this type.
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
      GameMessageWrapper { _tab: table }
    }

    #[inline]
    pub fn message(&self) -> Option<::flatbuffers::Table<'a>> {
      unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Self::VT_MESSAGE, None) }
    }

    #[inline]
    pub fn message_as_player_stat_event(&self) -> Option<PlayerStatEvent<'a>> {
      if self.message_type() == GameMessage::PlayerStatEvent {
        self.message().map(|t| unsafe { PlayerStatEvent::init_from_table(t) })
      } else {
        None
      }
    }

    #[inline]
    pub fn message_as_player_spectate(&self) -> Option<PlayerSpectate<'a>> {
      if self.message_type() == GameMessage::PlayerSpectate {
        self.message().map(|t| unsafe { PlayerSpectate::init_from_table(t) })
      } else {
        None
      }
    }

    #[inline]
    pub fn message_as_player_input_change(&self) -> Option<PlayerInputChange<'a>> {
      if self.message_type() == GameMessage::PlayerInputChange {
        self.message().map(|t| unsafe { PlayerInputChange::init_from_table(t) })
      } else {
        None
      }
    }
  }

  impl ::flatbuffers::Verifiable for GameMessageWrapper<'_> {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.visit_table(pos)?
        .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'_>>>("Message", Self::VT_MESSAGE, false)?
        .finish();
      Ok(())
    }
  }

  impl ::core::fmt::Debug for GameMessageWrapper<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      let mut ds = f.debug_struct("GameMessageWrapper");
      ds.field("Message", &self.message());
      ds.finish()
    }
  }

  pub struct GameMessageWrapperBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
  }

  impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GameMessageWrapperBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
      self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GameMessageWrapper::VT_MESSAGE, message);
    }

    #[inline]
    pub fn new(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GameMessageWrapperBuilder<'a, 'b, A> {
      let start = fbb.start_table();
      GameMessageWrapperBuilder { fbb_: fbb, start_: start }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<GameMessageWrapper<'a>> {
      let o = self.fbb_.end_table(self.start_);
      ::flatbuffers::WIPOffset::new(o.value())
    }
  }

  pub struct GameMessageWrapperArgs<'a> {
    pub message: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
  }

  impl<'a> Default for GameMessageWrapperArgs<'a> {
    fn default() -> Self {
      GameMessageWrapperArgs {
        message: None,
      }
    }
  }

  #[inline]
  pub fn createGameMessageWrapper<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GameMessageWrapperArgs<'args>,
  ) -> ::flatbuffers::WIPOffset<GameMessageWrapper<'bldr>> {
    let mut builder = GameMessageWrapperBuilder::new(fbb);
    if let Some(x) = args.message { builder.add_message(x); }
    builder.finish()
  }

  // struct PossiblyReservedWords, aligned to 4
  #[repr(transparent)]
  #[derive(Clone, Copy, PartialEq)]
  pub struct PossiblyReservedWords(pub [u8; 16]);

  impl Default for PossiblyReservedWords {
    fn default() -> Self {
      Self([0; 16])
    }
  }

  impl ::core::fmt::Debug for PossiblyReservedWords {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
      f.debug_struct("PossiblyReservedWords")
        .field("follow", &self.follow())
        .field("push", &self.push())
        .field("size", &self.size())
        .field("alignment", &self.alignment())
        .finish()
    }
  }

  impl PossiblyReservedWords {
    pub fn new(follow: f32, push: f32, size: f32, alignment: f32) -> Self {
      let mut s = Self([0; 16]);
      s.set_follow(follow);
      s.set_push(push);
      s.set_size(size);
      s.set_alignment(alignment);
      s
    }

    pub fn follow(&self) -> f32 {
      let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
      ::flatbuffers::EndianScalar::from_little_endian(unsafe {
        ::core::ptr::copy_nonoverlapping(
          self.0[0..].as_ptr(),
          mem.as_mut_ptr() as *mut u8,
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
        mem.assume_init()
      })
    }

    pub fn set_follow(&mut self, follow: f32) {
      let follow_le = ::flatbuffers::EndianScalar::to_little_endian(follow);
      unsafe {
        ::core::ptr::copy_nonoverlapping(
          &follow_le as *const _ as *const u8,
          self.0[0..].as_mut_ptr(),
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
      }
    }

    pub fn push(&self) -> f32 {
      let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
      ::flatbuffers::EndianScalar::from_little_endian(unsafe {
        ::core::ptr::copy_nonoverlapping(
          self.0[4..].as_ptr(),
          mem.as_mut_ptr() as *mut u8,
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
        mem.assume_init()
      })
    }

    pub fn set_push(&mut self, push: f32) {
      let push_le = ::flatbuffers::EndianScalar::to_little_endian(push);
      unsafe {
        ::core::ptr::copy_nonoverlapping(
          &push_le as *const _ as *const u8,
          self.0[4..].as_mut_ptr(),
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
      }
    }

    pub fn size(&self) -> f32 {
      let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
      ::flatbuffers::EndianScalar::from_little_endian(unsafe {
        ::core::ptr::copy_nonoverlapping(
          self.0[8..].as_ptr(),
          mem.as_mut_ptr() as *mut u8,
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
        mem.assume_init()
      })
    }

    pub fn set_size(&mut self, size: f32) {
      let size_le = ::flatbuffers::EndianScalar::to_little_endian(size);
      unsafe {
        ::core::ptr::copy_nonoverlapping(
          &size_le as *const _ as *const u8,
          self.0[8..].as_mut_ptr(),
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
      }
    }

    pub fn alignment(&self) -> f32 {
      let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
      ::flatbuffers::EndianScalar::from_little_endian(unsafe {
        ::core::ptr::copy_nonoverlapping(
          self.0[12..].as_ptr(),
          mem.as_mut_ptr() as *mut u8,
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
        mem.assume_init()
      })
    }

    pub fn set_alignment(&mut self, alignment: f32) {
      let alignment_le = ::flatbuffers::EndianScalar::to_little_endian(alignment);
      unsafe {
        ::core::ptr::copy_nonoverlapping(
          &alignment_le as *const _ as *const u8,
          self.0[12..].as_mut_ptr(),
          ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
        );
      }
    }

  }

  impl<'a> ::flatbuffers::Follow<'a> for PossiblyReservedWords {
    type Inner = &'a PossiblyReservedWords;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      unsafe { <&'a PossiblyReservedWords>::follow(buf, loc) }
    }
  }

  impl<'a> ::flatbuffers::Follow<'a> for &'a PossiblyReservedWords {
    type Inner = &'a PossiblyReservedWords;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
      unsafe { ::flatbuffers::follow_cast_ref::<PossiblyReservedWords>(buf, loc) }
    }
  }

  impl<'b> ::flatbuffers::Push for PossiblyReservedWords {
    type Output = PossiblyReservedWords;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
      let src = unsafe { ::core::slice::from_raw_parts(self as *const PossiblyReservedWords as *const u8, <Self as ::flatbuffers::Push>::size()) };
      dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
      ::flatbuffers::PushAlignment::new(4)
    }
  }

  impl<'a> ::flatbuffers::Verifiable for PossiblyReservedWords {
    #[inline]
    fn run_verifier(v: &mut ::flatbuffers::Verifier, pos: usize) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
      v.in_buffer::<Self>(pos)
    }
  }

  impl ::flatbuffers::SimpleToVerifyInSlice for PossiblyReservedWords {}

} // RustNamerTest
