[package]
name = "flatc-rs-wasm"
version = "0.1.0"
edition = "2021"
description = "WASM bindings for the FlatBuffers Rust compiler"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
flatc-rs-codegen = { path = "../codegen" }
flatc-rs-compiler = { path = "../compiler" }
flatc-rs-annotator = { path = "../annotator" }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
